### ISSUE TITLE
During installation  of  tool using go, package crypto/ecdh is not in GOROOT issue occurs!

### ISSUE THREAD

**Issue by Prajwal-PS7** [projectdiscovery/subfinder#1000]
Find the error code line.

```
└─$ go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
../pkg/mod/github.com/refraction-networking/utls@v1.5.2/cfkem.go:25:2: package crypto/ecdh is not in GOROOT (/usr/src/crypto/ecdh)

**Comment by MetzinAround** [comment]
From what I've seen before this might have something to do with your Go version. What version of Go are you running?

**Comment by Prajwal-PS7** [comment]
> From what I've seen before this might have something to do with your Go version. What version of Go are you running?

I'm using 

```
go version go1.18 gccgo (Debian 13.2.0-4) 13.2.0 linux/amd64
```

**Comment by Prajwal-PS7** [comment]
Issue resolved !!

Found the root cause; GOROOT and GOPATH environment variables was misconfigured.

Resolved this issue by running following command:
```
└─$ sudo apt install golang
```

**Comment by MetzinAround** [comment]
Thank you @Prajwal-PS7 for posting your solution!
