### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd8fa75]

### ISSUE THREAD

**Issue by G3X1337** [projectdiscovery/subfinder#1015]
<img width="927" alt="Screenshot 2023-10-12 141601" src="https://github.com/projectdiscovery/subfinder/assets/76747867/ebda08e2-cfc2-4f80-a495-f39dd02aa366">

**Comment by dogancanbakir** [comment]
@G3X1337,
Could you please let me know which version of `subfinder` you are currently using?

**Comment by G3X1337** [comment]
> @G3X1337, Could you please let me know which version of `subfinder` you are currently using?

v2.6.0

**Comment by dogancanbakir** [comment]
@G3X1337,
This is probably fixed in  [v2.6.1](https://github.com/projectdiscovery/subfinder/releases/tag/v2.6.1). Can you try with the latest version?

**Comment by G3X1337** [comment]
> @G3X1337, This is probably fixed in [v2.6.1](https://github.com/projectdiscovery/subfinder/releases/tag/v2.6.1). Can you try with the latest version [v.2.6.3](https://github.com/projectdiscovery/subfinder/releases/tag/v2.6.3)?

how to auto update on kali linux?

**Comment by dogancanbakir** [comment]
@G3X1337,
You can use `-up, -update                 update subfinder to latest version` flag or follow installation instructions at https://github.com/projectdiscovery/subfinder#installation.

**Comment by G3X1337** [comment]
> @G3X1337, You can use `-up, -update update subfinder to latest version` flag or follow installation instructions at https://github.com/projectdiscovery/subfinder#installation.

ok thanks brother

**Comment by dogancanbakir** [comment]
@G3X1337,
Assuming your issue has been resolved since I haven't heard back from you. Closing this, feel free to reopen it if the problem persists.
