### ISSUE TITLE
[Issue]  install subfinder latest version error

### ISSUE THREAD

**Issue by betta-cyber** [projectdiscovery/subfinder#1021]
**Describe the bug**
go1.19.5 darwin/arm64 install subfinder latest version error

**Subfinder version**
Include the version of subfinder you are using, `subfinder -version`

```
go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
../../go/pkg/mod/github.com/refraction-networking/utls@v1.5.2/cfkem.go:25:2: package crypto/ecdh is not in GOROOT (/opt/homebrew/Cellar/go/1.19.5/libexec/src/crypto/ecdh)
```

**Comment by dogancanbakir** [comment]
@betta-cyber,
Would you be willing to update Go and give it another try? Also, clearing Go's cache can help resolve some problems related to package inconsistencies or old cached data `go clean -modcache`

**Comment by dogancanbakir** [comment]
Closing this. Feel free to reopen if the issue continues.
