### ISSUE TITLE
Install subfinder error from checkCurrentUserRoot

### ISSUE THREAD

**Issue by jordyherrerariveralg** [projectdiscovery/subfinder#1046]
Hello help
Couldnt I install termux on my device and root it for Android?
what about termux by subfinder anyone problem package permissionutil? go/pkg/mod/github.com/projectdiscovery/utils@v0.0.54/permission/permission_other.go 
![Screenshot_20231118-223023_Termux](https://github.com/projectdiscovery/subfinder/assets/130174489/2c940252-2622-4701-a201-c09a32923cb1)

**Comment by dogancanbakir** [comment]
@jordyherrerariveralg, Thanks for opening this issue. This will be fixed with the next release—details at https://github.com/projectdiscovery/subfinder/pull/1053. In the meantime, you can use the `dev` branch as a temporary solution.
