### ISSUE TITLE
go: github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest: GOPROXY list is not the empty string, but contains no entries

### ISSUE THREAD

**Issue by sey8** [projectdiscovery/subfinder#1062]
go: github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest: GOPROXY list is not the empty string, but contains no entries

**Comment by dogancanbakir** [comment]
@sey8, Thanks for opening this issue. It looks like you're facing an issue with the `GOPROXY` configuration while installing `subfinder`. Here's a quick fix you can try:

1. First, check your current `GOPROXY` setting:
   ```
   go env GOPROXY
   ```

2. If it's not set correctly, update it to the default Go proxy:
   ```
   go env -w GOPROXY=https://proxy.golang.org,direct
   ```

3. After setting the `GOPROXY`, try installing `subfinder` again:
   ```
   go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
   ```

If the issue persists, please ensure your Go environment is correctly configured, including `GOPATH` and `GOROOT`, and that your Go version is up to date.

Hope this helps!
