### ISSUE TITLE
[Issue] Subfinder will respond with an EOF warning if the results from RapidDNS are too large

### ISSUE THREAD

**Issue by egru** [projectdiscovery/subfinder#1073]
**Describe the bug**
When using RapidDNS as a source, if the results are too large, subfinder will returns an EOF warning. This appears to be related to gzip compression from what I've been reading, but I haven't been able to determine a fix for it.

**Subfinder version**
v2.6.3

**Complete command you used to reproduce this**
subfinder -s rapiddns -d facebook.com -v

**Screenshots**
![Screenshot 2023-12-06 - 10 43 40](https://github.com/projectdiscovery/subfinder/assets/381117/e9d6432c-71ec-4071-ab31-ed12ffe9e283)

**Comment by LuD1161** [comment]
Hey @egru 👋 
Thanks for reporting this 😄 
I am trying to reproduce this and I get the following - 
<img width="585" alt="image" src="https://github.com/projectdiscovery/subfinder/assets/17861054/fe760941-0eac-4da4-936a-50aa552aa5b7">

**Comment by egru** [comment]
Hmm. I just checked this on different systems on different networks and sure enough it's working. There must be something goofy going on with the network I was testing it on. You can close this issue. Thanks!
