### ISSUE TITLE
Concerning the issue with the API and advice on dictionary-based brute-force attacks

### ISSUE THREAD

**Issue by WasteMaterial** [projectdiscovery/subfinder#1088]
Hello, how should I handle the situation when I'm unsure about the correct format while adding an API? 
Additionally, does Subfinder support using a dictionary for brute-force attacks after passively obtaining subdomains?
![image](https://github.com/projectdiscovery/subfinder/assets/32891131/3b0f3ad9-c9bf-45dc-abd6-53cf152c08da)

**Comment by dogancanbakir** [comment]
@WasteMaterial,
Make sure the yaml format is valid and you can also use `  -cs, -collect-sources    include all sources in the output (-json only)` flag to include sources in result. And, consider subfinder as passive subdomain enumeration tool, for bruteforce or resolving, we have [shuffledns](https://github.com/projectdiscovery/shuffledns) and [dnsx](https://github.com/projectdiscovery/dnsx).

**Comment by WasteMaterial** [comment]
> @WasteMaterial， 确保 yaml 格式有效，您还可以使用` -cs, -collect-sources include all sources in the output (-json only)`标志在结果中包含源。并且，将 subfinder 视为被动子域枚举工具，为了暴力破解或解析，我们有[shuffledns](https://github.com/projectdiscovery/shuffledns)和[dnsx](https://github.com/projectdiscovery/dnsx)。

All right! Thank you for your answer
