### ISSUE TITLE
subfinder API source list not showing correct results

### ISSUE THREAD

**Issue by kiro6** [projectdiscovery/subfinder#1094]
**Describe the bug**
 `subfinder -ls` do not show correct results , i have github,shodan api keys when i use  `subfinder -ls` it show that it does not exist and when i use `subfinder -s github -d example.com -v` it uses the key with no proplem , i did not change the `/provider-config.yaml` file it's the same 

**Subfinder version**
`v2.6.3 (latest)` in both kali linux wsl and windows 

**Complete command you used to reproduce this**
```
subfinder -ls
subfinder -s github -d example.com -v
```

**Screenshots**
![Screenshot_116](https://github.com/projectdiscovery/subfinder/assets/57776872/061457ce-3c2b-4c52-94b5-0acfda62bc52)

![Screenshot_115](https://github.com/projectdiscovery/subfinder/assets/57776872/ae9e4ef5-dd41-489d-b9b0-2477eb83fd92)

**Comment by dogancanbakir** [comment]
When you run `subfinder -ls`, just like the` -help` mentions, it's all about showing you the sources you've got. It's like taking a quick peek at what's available – `-ls, -list-sources` is your go-to. But it won't check if these sources are all set up. It's just a list, nothing more. Is that what you were trying to figure out?

**Comment by kiro6** [comment]
as i understand , when ` subfinder -ls` is used it to  show the sources i've got and whether the source have the api key or not as in `[INF] Sources marked with an * need key(s) or token(s) to work.` , in my case as the screenshot it say shodan and github do not have api keys but they already have

**Comment by dogancanbakir** [comment]
No, it works as I explained in the [previous comment](https://github.com/projectdiscovery/subfinder/issues/1094#issuecomment-1873816913).
See:
https://github.com/projectdiscovery/subfinder/blob/dev/v2/pkg/runner/options.go#L194
https://github.com/projectdiscovery/subfinder/blob/dev/v2/pkg/runner/options.go#L223
https://github.com/projectdiscovery/subfinder/blob/dev/v2/pkg/runner/options.go#L231 -it only checks whether the source needs a key.

**Comment by kiro6** [comment]
thanks very much
