### ISSUE TITLE
[Issue] fofa source does't work

### ISSUE THREAD

**Issue by yaoyi2008** [projectdiscovery/subfinder#1098]
**Describe the bug**
配置了fofa的key，并且运行的时候也提示发现了API key，但同时也提示no API key/secret defined for it.
同样的，我配置quake的API key就可以正常工作

**Subfinder version**
[INF] Current Version: v2.6.3

**Complete command you used to reproduce this**
subfinder -d example.com -s fofa -v

**Screenshots**
<img width="786" alt="image" src="https://github.com/projectdiscovery/subfinder/assets/5906825/cf0c2059-ca54-475e-bad5-31732c5c55bb">
<img width="618" alt="image" src="https://github.com/projectdiscovery/subfinder/assets/5906825/34e06835-d6f1-4574-96c7-20947d36771b">

**Comment by dogancanbakir** [comment]
> Composite keys for sources like, Censys, PassiveTotal, Fofa, Intellix and 360quake, need to be separated with a colon (:).

In case of `fofa`, it should be `email:secret`.
See https://github.com/projectdiscovery/subfinder#post-installation-instructions
