### ISSUE TITLE
fix windows colors support

### ISSUE THREAD

**Issue by picatz** [projectdiscovery/subfinder#112]
## What's the problem (or question)?
Color support doesn't work on `Microsoft Windows 10` (and probably other version).

## Do you have an idea for a solution?
Use a cross-platform color support library, or don't use color on windows.

## How can we reproduce the issue?
On windows:
1. `choco install golang`
2. `go get github.com/subfinder/subfinder`
3. `/path/to/sunfinder.exe` has broken colors

**Comment by Ice3man543** [comment]
Hey, this should be fixed in the latest release. Closing this now!
