### ISSUE TITLE
[Issue] [homebrew] 2.6.4 regression test build failed 

### ISSUE THREAD

**Issue by chenrui333** [projectdiscovery/subfinder#1124]
**Describe the bug**

With #1013 change, now the config path exists in a different path other than `.config/subfinder` for osx build. 

**Subfinder version**
2.6.4

**Complete command you used to reproduce this**
- go build the binary
- subfinder run

linux build log

```
[INF] Current subfinder version v2.6.4 (latest)
[INF] Loading provider config from /tmp/subfinder-test-20240111-7156-8lxjsn/.config/subfinder/provider-config.yaml
[INF] Enumerating subdomains for brew.sh
```

macos build log

```
[INF] Current subfinder version v2.6.4 (latest)
[INF] Loading provider config from /private/tmp/subfinder-test-20240111-73655-dcnsru/Library/Application Support/subfinder/provider-config.yaml
[INF] Enumerating subdomains for brew.sh
```

---

relates to https://github.com/Homebrew/homebrew-core/pull/159690

**Comment by dogancanbakir** [comment]
This is expected. We're using the `UserConfigDir` func from `os` pkg to generate os-specific config dir. See: https://cs.opensource.google/go/go/+/refs/tags/go1.21.6:src/os/file.go;l=447. Let us know if you have further questions.
