### ISSUE TITLE
Alienvault Missing

### ISSUE THREAD

**Issue by motoko-ayanami** [projectdiscovery/subfinder#1151]
Hello,

It seems like alienvault is missing from the default config template. Apparently it still works though if used as a source.

**Comment by dogancanbakir** [comment]
alienvault doesn't require a key, which is why it's not in the provider config file. See https://github.com/projectdiscovery/subfinder/blob/dev/v2/pkg/subscraping/sources/alienvault/alienvault.go#L88. I believe this is what you're asking for; if not, feel free to reopen and let us know.
