### ISSUE TITLE
`-silent` function not working!

### ISSUE THREAD

**Issue by 0xhunster** [projectdiscovery/subfinder#1204]
hello team,
when I typed the command `subfinder -d google.com -s shodan -silent`, I saw the `-silent` function was not working.

![image](https://github.com/projectdiscovery/subfinder/assets/46501627/05cd5d5e-c4bf-4940-99a5-08914e3ef1bd)

**Comment by DhiyaneshGeek** [comment]
Hi @0xhunster Can you check again with the new release , it's working as intended

```
geekfreak@~ % subfinder -d hackerone.com -s shodan -silent
[INF] Current subfinder version v2.6.6 (latest)
b.ns.hackerone.com
docs.hackerone.com
zendesk1.hackerone.com
_dmarc.hackerone.com
mta-sts.managed.hackerone.com
resources.hackerone.com
support.hackerone.com
api.hackerone.com
gslink.hackerone.com
mta-sts.hackerone.com
mta-sts.forwarding.hackerone.com
www.hackerone.com
zendesk2.hackerone.com
```

**Comment by 0xhunster** [comment]
I said for `-silent` function. could you see your result? there is version info showing inside the -silent mode.

`[INF] Current subfinder version v2.6.6 (latest)`
