### ISSUE TITLE
Subfinder Logo

### ISSUE THREAD

**Issue by ZeroDot1** [projectdiscovery/subfinder#122]
I think Subfinder should have a logo, I quickly created a simple logo.

[Subfinder_Logo_ASCII.txt](https://github.com/subfinder/subfinder/files/2195837/Subfinder_Logo_ASCII.txt)
![subfinder_logo](https://user-images.githubusercontent.com/28985171/42735394-43d328be-8853-11e8-9b89-82bb2895ad25.png)

**Comment by codingo** [comment]
@picatz has a good proposal here: https://twitter.com/KentGruber/status/1015602133469671425

This looks like the most likely candidate at present.

**Comment by picatz** [comment]
@ZeroDot1 👋 Hello again! Thanks for taking interest in this issue. 👨‍🎨 

I agree that SubFinder should have a new logo. As @codingo shared, I was also playing around with this idea. I love that you took the time to make something too. ❤️
