### ISSUE TITLE
Add Pulsedive.com

### ISSUE THREAD

**Issue by ZeroDot1** [projectdiscovery/subfinder#124]
Pulsedive lists a lot of subdomains, and I think it would be helpful if Subfinder can also search Pulsedive for subdomains.
Example: https://pulsedive.com/browse/?q=eyJ2YWx1ZSI6ImNvaW5oaXZlLmNvbSIsInR5cGUiOlsiYXJ0aWZhY3QiLCJkb21haW4iLCJpcCIsInVybCJdLCJyaXNrIjpbInVua25vd24iLCJub25lIiwibG93IiwibWVkaXVtIiwiaGlnaCIsImNyaXRpY2FsIl0sImF0dHJpYnV0ZSI6W3siaHRtbHNhZmUiOnsidmFsdWUiOiJTdWJkb21haW4iLCJuYW1lIjoiSG9zdCBUeXBlIiwidHlwZSI6ImF0dHJpYnV0ZSJ9LCJyYXciOnsidmFsdWUiOiJTdWJkb21haW4iLCJuYW1lIjoiaG9zdHR5cGUiLCJ0eXBlIjoiYXR0cmlidXRlIiwiaWQiOjIwfX1dLCJwcm9wZXJ0eSI6W10sImxhdGVzdCI6WyJoaXN0b3JpY2FsIl0sInRocmVhdCI6W10sImZlZWQiOltdLCJsYXN0c2VlbiI6WyJhbGwiXX0= 
![bildschirmfoto vom 2018-07-18 16-11-40](https://user-images.githubusercontent.com/28985171/42887098-76843fa6-8aa5-11e8-9fd7-f0128385ce0f.png)

**Comment by Ice3man543** [comment]
This seems interesting. We'll work on it.

**Comment by marataziat** [comment]
Can I do this?

**Comment by Ice3man543** [comment]
@marataziat sure, you can do this

**Comment by Ice3man543** [comment]
Hey @ZeroDot1, not sure how effective it is and how it works! If you can provide some more info, i can work on this!

**Comment by ZeroDot1** [comment]
I recommend you look at the API: https://pulsedive.com/api/ 
https://github.com/viiftw/pulsedive-go

**Comment by buivancuong** [comment]
Pulsedive is the reliable resource, I think this integrated feature will be helpful, the Go Pulsedive API is very well: https://github.com/viiftw/pulsedive-go

**Comment by buivancuong** [comment]
Pulsedive is the reliable resource, I think this integrated feature will be helpful, the Go Pulsedive API is very well.

**Comment by vzamanillo** [comment]
There are some things that we have to consider when adding this source, we can add a source that consumes data directly from the API (API key would be needed) or we can add a source that does an HTTP POST to the public search page (no I would need API Key) but it is limited to 100 results, or we can use one or the other depending on whether there is an API key for pulsedive in the config file. Any thoughts?

**Comment by bauthard** [comment]
When API is available (in this yes) we always prefer to use API. 

> but it is limited to 100 results

If this is true, it will be overhead to use it as `pulsedive` also have 1 request / 2-second limit.

**Comment by bauthard** [comment]
Closing this one, as we will focusing on utilizing existing sources in the best possible way, new sources will be added only when we are getting new results using new sources compared to existing sources.
