### ISSUE TITLE
There is no source with the name: archiveis

### ISSUE THREAD

**Issue by ddol31721** [projectdiscovery/subfinder#1252]
### Steps To Reproduce:

```
./subfinder -d google.com

               __    _____           __
   _______  __/ /_  / __(_)___  ____/ /__  _____
  / ___/ / / / __ \/ /_/ / __ \/ __  / _ \/ ___/
 (__  ) /_/ / /_/ / __/ / / / / /_/ /  __/ /
/____/\__,_/_.___/_/ /_/_/ /_/\__,_/\___/_/

                projectdiscovery.io

[INF] Current subfinder version v2.6.6 (latest)
[INF] Loading provider config from /root/.config/subfinder/provider-config.yaml
[FTL] There is no source with the name: archiveis
```

### Anything else:

```[tasklist]
### Tasks
```

**Comment by dogancanbakir** [comment]
The source you're trying to use is removed a while ago. See the PR https://github.com/projectdiscovery/subfinder/pull/655. What can I help you with?

**Comment by ddol31721** [comment]
[FTL] There is no source with the name: archiveis

**Comment by dogancanbakir** [comment]
Can you remove `archives` entry from` /root/.config/subfinder/provider-config.yaml` and retry it ?

**Comment by dogancanbakir** [comment]
Closing this. Feel free to reopen if the issue persists.

**Comment by Prisoner2-6-7** [comment]
> Can you remove `archiveis` entry from` /root/.config/subfinder/provider-config.yaml` and retry it ?

cat /home/parrot/.config/subfinder/provider-config.yaml | grep archiveis

parrot in 🌐 parrotos in /tmp
❯ subfinder -d hackerone.com -oJ -active -silent
[INF] Current subfinder version v2.6.6 (latest)
[FTL] There is no source with the name: archiveis

parrot in 🌐 parrotos in /tmp
❯ subfinder -ls

               __    _____           __
   _______  __/ /_  / __(_)___  ____/ /__  _____
  / ___/ / / / __ \/ /_/ / __ \/ __  / _ \/ ___/
 (__  ) /_/ / /_/ / __/ / / / / /_/ /  __/ /
/____/\__,_/_.___/_/ /_/_/ /_/\__,_/\___/_/

                projectdiscovery.io

[INF] Current subfinder version v2.6.6 (latest)
[INF] Current list of available sources. [39]
[INF] Sources marked with an * need key(s) or token(s) to work.
[INF] You can modify /home/parrot/.config/subfinder/provider-config.yaml to configure your keys/tokens.
