### ISSUE TITLE
Add the WHOIS API from IP2Whois.com

### ISSUE THREAD

**Issue by ip2location** [projectdiscovery/subfinder#1259]
### Please describe your feature request:

Add the WHOIS API from https://www.ip2whois.com/developers-api which would be a good option to have, in addition to the existing whoisxml API.

**Comment by dogancanbakir** [comment]
Getting 
<img width="1384" alt="image" src="https://github.com/projectdiscovery/subfinder/assets/65292895/4dfdb9b7-35c7-47e9-9e86-df06bc67875b">

**Comment by dogancanbakir** [comment]
Every time I check, the provider is down. Therefore, adding an unstable provider won't provide additional value. So, closing this. Feel free to reopen if you think otherwise.

**Comment by ip2location** [comment]
@dogancanbakir May we know which domains are you querying that you encountered with the error?

**Comment by dogancanbakir** [comment]
https://www.ip2whois.com/developers-api

**Comment by ip2location** [comment]
You mean you are getting ERROR 502 when you access https://www.ip2whois.com and https://www.ip2whois.com/developers-api pages?

**Comment by dogancanbakir** [comment]
Yes, that's correct.

**Comment by ip2location** [comment]
@dogancanbakir Please try again and see if you still get the 502 error.

**Comment by dogancanbakir** [comment]
Same
<img width="615" alt="image" src="https://github.com/projectdiscovery/subfinder/assets/65292895/4b0d3ab7-3460-4777-bbb9-e048497ffec6">
