### ISSUE TITLE
The current version continues to print output despite the '-silent' flag being provided

### ISSUE THREAD

**Issue by 0xh7ml** [projectdiscovery/subfinder#1294]
**Describe the bug**
While using subfinder with silent flag, the banner is not printing to terminal, but the version info is printing to the terminal

**Subfinder version**
version v2.6.6 (latest)

**Complete command you used to reproduce this**
`subfinder -d <your_target> -silent`

**Screenshots**
![2024-06-25_125956](https://github.com/projectdiscovery/subfinder/assets/42938253/425fd553-cf3d-4693-97ba-52b88f778647)

**Comment by dogancanbakir** [comment]
The issue will be resolved in the next release.
