### ISSUE TITLE
Apple Silicon 

### ISSUE THREAD

**Issue by L33t33L** [projectdiscovery/subfinder#1300]
Running almost all Go-written tools on an ARM64 system ( Kali Linux on a MacBook M2) results in "zsh: exec format error".

**Comment by n0n0nroot** [comment]
Fixed issue via 
GOARCH=arm64 GOOS=linux go build -o subfinder 
but do i need to do each time for installing go tools to M2 chip ?

**Comment by dogancanbakir** [comment]
What is the current version of Go installed on your system?
