### ISSUE TITLE
There is no source with the name: riddler

### ISSUE THREAD

**Issue by arzikamubarak** [projectdiscovery/subfinder#1302]
whenever i try to run subfinder i get this error, and i have been using it before

/subfinder -d hackerone.com

               __    _____           __         
   _______  __/ /_  / __(_)___  ____/ /__  _____
  / ___/ / / / __ \/ /_/ / __ \/ __  / _ \/ ___/
 (__  ) /_/ / /_/ / __/ / / / / /_/ /  __/ /    
/____/\__,_/_.___/_/ /_/_/ /_/\__,_/\___/_/

		projectdiscovery.io

[INF] Current subfinder version v2.6.6 (latest)
[INF] Loading provider config from /home/moon_shadow/.config/subfinder/provider-config.yaml
[FTL] There is no source with the name: riddler

**Comment by dogancanbakir** [comment]
Unfortunately, this source is not supported right now. You can disable it in your config file. Please refer to https://github.com/projectdiscovery/subfinder/pull/1111.
