### ISSUE TITLE
Integration Request for Subdomain Center API

### ISSUE THREAD

**Issue by g147** [projectdiscovery/subfinder#1309]
Hello!

Last year, I released an API called Subdomain Center. Due to its aggressive rate limits, which was the reason provided, it couldn't be integrating into the Subfinder project -  https://github.com/projectdiscovery/subfinder/pull/835

However, I have noticed that Subfinder now supports other providers with rate limits. Moreover, we now give rate limit free access to our paid users - https://www.arpsyndicate.io/pricing.html 

Given these updates, I believe it is now feasible to integrate the Subdomain Center API into Subfinder. 

API Details:
Endpoint: https://api.subdomain.center/
Documentation: https://github.com/ARPSyndicate/docs?tab=readme-ov-file#subdomain-center
Rate Limits: 2/minutes

I am confident that integrating Subdomain Center will enhance Subfinder's capabilities and provide users with more comprehensive results. Please let me know if there are any additional details or requirements needed for this integration.

Thanks!

**Comment by GeorginaReeder** [comment]
Thanks so much for your suggestion @g147 , we'll take a look into this!

**Comment by ahmedredwanridoy** [comment]
<U>TEST</U>

**Comment by ahmedredwanridoy** [comment]
</p><u>Test</u>
