### ISSUE TITLE
[FTL] There is no source with the name: riddler

### ISSUE THREAD

**Issue by risinghunter1411** [projectdiscovery/subfinder#1322]
I am facing the following issue with my subfinder
<img width="811" alt="Screenshot 2024-07-25 at 6 17 05 PM" src="https://github.com/user-attachments/assets/09994ac8-2a24-4c2e-8b63-1b993a602ad5">

Please help me resolve the issue.

**Comment by dogancanbakir** [comment]
Would you happen to have a config for riddler in the `provider-config.yaml` file?

**Comment by risinghunter1411** [comment]
there is no such thing as `riddler` present in the `provider-config.yaml ` file
<img width="1017" alt="Screenshot 2024-07-25 at 7 25 48 PM" src="https://github.com/user-attachments/assets/911f3c53-3b20-47d8-a2b1-25488178bb5d">
<img width="1017" alt="Screenshot 2024-07-25 at 7 26 29 PM" src="https://github.com/user-attachments/assets/79a59c55-7590-4370-b7a9-8edd96b70198">

**Comment by risinghunter1411** [comment]
There is no configuration for `riddler` present in the `provider-config.yaml` file. please check the following screenshots.
<img width="1017" alt="Screenshot 2024-07-26 at 10 59 55 AM" src="https://github.com/user-attachments/assets/3751ed60-2b3b-4e56-b7b2-ee08369c018c">
<img width="1017" alt="Screenshot 2024-07-25 at 7 26 29 PM" src="https://github.com/user-attachments/assets/9113ff75-e294-48bb-a713-c608c86fb11c">

**Comment by dogancanbakir** [comment]
Could you `subfinder -ls `?

**Comment by risinghunter1411** [comment]
<img width="1001" alt="Screenshot 2024-07-31 at 4 10 03 PM" src="https://github.com/user-attachments/assets/5b4c828a-ff25-40f6-9ef5-1068b37a5543">

**Comment by dogancanbakir** [comment]
Here, this is what I get when I run it:

```console
$ subfinder -d hackerone.com 

               __    _____           __         
   _______  __/ /_  / __(_)___  ____/ /__  _____
  / ___/ / / / __ \/ /_/ / __ \/ __  / _ \/ ___/
 (__  ) /_/ / /_/ / __/ / / / / /_/ /  __/ /    
/____/\__,_/_.___/_/ /_/_/ /_/\__,_/\___/_/

                projectdiscovery.io

[INF] Current subfinder version v2.6.6 (latest)
[INF] Loading provider config from /Users/dogancanbakir/Library/Application Support/subfinder/provider-config.yaml
[INF] Enumerating subdomains for hackerone.com
...
[INF] Found 39 subdomains for hackerone.com in 5 seconds 230 milliseconds
```

The only remaining advice I can give is to remove it completely (including configs) and reinstall it again.

**Comment by risinghunter1411** [comment]
I removed the subfinder first completely (including configs) and reinstalled it again. but getting same error
<img width="991" alt="Screenshot 2024-08-10 at 6 54 28 PM" src="https://github.com/user-attachments/assets/661d8173-6d18-4538-a1a2-17367d264b82">

**Comment by Cgboal** [comment]
Deleting these two files then running subfinder again will fix it @risinghunter1411 

```normal
❯ rm ~/Library/Application\ Support/subfinder/config.yaml
❯ rm ~/Library/Application\ Support/subfinder/provider-config.yaml
```
