### ISSUE TITLE
[ ISSUE ] open subfinder/config.yaml: no such file or directory

### ISSUE THREAD

**Issue by cbxcvl** [projectdiscovery/subfinder#1324]
### Subfinder version:
v2.6.6

### Current Behavior:
When I run the command `echo example.com | subfinder -silent -duc | sort -u`, I get the following error:

open subfinder/config.yaml: no such file or directory

### Expected Behavior:
The command should run successfully and output the subdomains of the given domain without any errors.

### Steps To Reproduce:
1. Execute the command `echo example.com | subfinder -silent -duc | sort -u`
2. Observe the error: `open subfinder/config.yaml: no such file or directory`

### Anything else:

I have both `provider-config.yaml` and `config.yaml` files in the directory `/root/.config/subfinder/`, but the issue persists.

**Comment by dogancanbakir** [comment]
What's the output of `go run . -d scanme.sh` ? Also, I assume you're on linux?
