### ISSUE TITLE
[Issue] rapiddns pagination error

### ISSUE THREAD

**Issue by yq1ng** [projectdiscovery/subfinder#1330]
**Subfinder version**
v2.6.6

**Screenshots**
The front end of rapiddns.io might have been updated, and the original pagination regex for subfinder is no longer applicable. I temporarily modified it to class="page-link".*>(\d+)</a></li>, which can be recognized correctly.
![image](https://github.com/user-attachments/assets/667f0cb3-889d-4cd4-9fa8-ad30993473bb)

**Comment by yq1ng** [comment]
When there are too many results, adding the URL parameter `&full=1` seems to work better, as the front end returns a maximum of 100 pages. Additionally, I've noticed that the results seem to remain the same when the page number changes.

**Comment by dogancanbakir** [comment]
@yq1ng Thanks for letting us know! I've updated the regex pattern and raised a PR.
