### ISSUE TITLE
[Issue] stats shows negative values

### ISSUE THREAD

**Issue by six2dez** [projectdiscovery/subfinder#1366]
**Describe the bug**
Trying to get some stats from subfinder I've found the stats option always shows negative values for bevigil and commoncrawl

**Subfinder version**
v2.6.6

**Complete command you used to reproduce this**
`subfinder -d domain.com -all -stats -v`

**Screenshots**
![image](https://github.com/user-attachments/assets/6ce69524-ebde-4694-b472-614043804a7a)

**Comment by tarunKoyalwar** [comment]
@six2dez if i am not wrong the negative stats are meant to indicate errors while 0 indicates no results

**Comment by dogancanbakir** [comment]
Thanks for opening this issue. As @tarunKoyalwar pointed out, this might be because of errors, but IMO still can be confusing. I'll look into it.

**Comment by tarunKoyalwar** [comment]
after validating this seems to be a bug and not a intentional feature because we already have a dedicated errors column , it mistook this with something else
