### ISSUE TITLE
[Feature Request] Line-based File Scanning

### ISSUE THREAD

**Issue by Bundy01** [projectdiscovery/subfinder#1399]
### Please describe your feature request:

Some sources are limited in requests, and adding an option to read a file (with the `-dL` option) by lines and then quit Subfinder would be a plus.
For ex:
```sh
subfinder -lines 1,50 -nW -dL FILE
```

### Describe the use case of this feature:

At the moment, I manually go down the first 50 lines to the end of the file and so on.
The following command would save me the trouble.
```
subfinder -lines 50,100 -nW -dL FILE
```

Regards.

**Comment by GeorginaReeder** [comment]
Thanks so much for your feature request @Bundy01 , we'll take a look into this!

**Comment by dogancanbakir** [comment]
This is a nice-to-have feature. You can easily do something like `sed -n '5,7p' FILE > subfinder...` instead of another flag.

Mentioning @ehsandeep for the discussion.

**Comment by Bundy01** [comment]
@dogancanbakir, I think the option would be preferable because not everyone knows the command you put in.

**Comment by Bundy01** [comment]
@dogancanbakir: I tested your command by replacing `>` with `|`.
This is the result I expected, so if you don't add this option in Subfinder, you can close this issue.
