### ISSUE TITLE
There is no source with the name: archiveis

### ISSUE THREAD

**Issue by Prisoner2-6-7** [projectdiscovery/subfinder#1401]
### Steps To Reproduce:

❯ subfinder -d hackerone.com -oJ -active -silent
[INF] Current subfinder version v2.6.6 (latest)
[FTL] There is no source with the name: archiveis

❯ subfinder -ls

[INF] Current subfinder version v2.6.6 (latest)
[INF] Current list of available sources. [39]
[INF] Sources marked with an * need key(s) or token(s) to work.
[INF] You can modify /home/parrot/.config/subfinder/provider-config.yaml to configure your keys/tokens.

cat /home/parrot/.config/subfinder/provider-config.yaml | grep archiveis

No Output

**Comment by dogancanbakir** [comment]
To troubleshoot this issue, please see https://github.com/projectdiscovery/subfinder/issues/1322. Closing this. Feel free to reopen if the issue persists.
