### ISSUE TITLE
columbus returns 5xx

### ISSUE THREAD

**Issue by dogancanbakir** [projectdiscovery/subfinder#1422]
Investigate the source, remove it if necessary. Details:

https://github.com/projectdiscovery/subfinder/actions/runs/11534818688/job/32109249708?pr=1421#step:5:1005

```console
    sources_wo_auth_test.go:74: 
        	Error Trace:	/home/runner/work/subfinder/subfinder/v2/pkg/passive/sources_wo_auth_test.go:74
        	Error:      	Not equal: 
        	            	expected: <nil>(<nil>)
        	            	actual  : *reflect.rtype(&reflect.rtype{t:abi.Type{Size_:0x8, PtrBytes:0x8, Hash:0x70cc2da0, TFlag:0x9, Align_:0x8, FieldAlign_:0x8, Kind_:0x36, Equal:(func(unsafe.Pointer, unsafe.Pointer) bool)(0x408c00), GCData:(*uint8)(0x142f0e8), Str:155098, PtrToThis:0}})
        	Test:       	TestSourcesWithoutKeys/columbus
        	Messages:   	columbus: unexpected status code 502 received from https://columbus.elmasy.com/api/lookup/hackerone.com
```

Initial PR for adding the source: https://github.com/projectdiscovery/subfinder/pull/1339

**Comment by Bundy01** [comment]
Yes, I noticed that with the new version of SubFinder.

I looked at the Columbus repository and there doesn't seem to be any activity for some time.

Would you have to be sure that the repository is no longer maintained before deleting this source?

https://github.com/elmasy-com/columbus/issues/7

**Comment by dogancanbakir** [comment]
Still the same. So, removing it.
