### ISSUE TITLE
[Issue] Too Many Errors With Bufferover

### ISSUE THREAD

**Issue by Bundy01** [projectdiscovery/subfinder#1433]
**Describe the bug**
Many errors with this source.

**Subfinder version**
Current Version: v2.6.7

**Complete command you used to reproduce this**
subfinder -s bufferover -d whatsapp.org -v

**Screenshots**
```console
[WRN] Encountered an error with source bufferover: error: failed to find exact match via binary search

```

**Comment by dogancanbakir** [comment]
This will only happen for specific targets, and the message you see originates directly from the API. Therefore, there isn’t much we can do about it. I will close this now. Don’t hesitate to reopen if you have any other questions.
