### ISSUE TITLE
Make failing sources non-default and exclude from tests

### ISSUE THREAD

**Issue by dogancanbakir** [projectdiscovery/subfinder#1440]
- [rapiddns.io](https://github.com/projectdiscovery/subfinder/actions/runs/11665041199/job/32476850100?pr=1421#step:5:984)
- [subdomain.center](https://github.com/projectdiscovery/subfinder/actions/runs/11665041199/job/32476850100?pr=1421#step:5:664)
- dnsdumpster

Note: These fail consistently across all builds. I will keep this issue open for feedback and comments for a while. Afterward, I will remove these sources.

**Comment by g147** [comment]
Hello @dogancanbakir!

Yes, the Subdomain Center's backend was impacted by a spike in load. However, I believe it is working fine now as I have scaled the backend.

Lmk if the issue persists & I'll be keeping an eye from my end too. 

Thanks!

**Comment by dogancanbakir** [comment]
As you know, we are always open to adding new sources. However, the recent failures have made us reconsider this approach. Ultimately, it impacts the user experience and quality. Therefore, while we appreciate your commitment to supporting your service, we can retain it for now. However, we cannot make any firm promises. If the issues persist, we will have to consider removing it in the future.

Thank you for your interest and for keeping this service running for the community.

**Comment by dogancanbakir** [comment]
@Bundy01 Thank you for sharing your insights. That’s another reason I'm keeping this issue open and will do so for a while. The plan is to track the sources, eliminate the bad ones, and enhance the quality.

**Comment by vortexau** [comment]
Rather than eliminating them entirely, could they be moved to a secondary group which needs a flag to re-enable them? Something like `--enable-flaky-sources` (for lack of a better name..) perhaps.
That way a casual user has a good experience, and advanced users can still access them, if they wish.

**Comment by g147** [comment]
Or maybe rank/cluster all the sources in terms of factors like availability, coverage, etc. That could help maybe in improving user experience.

**Comment by dogancanbakir** [comment]
@vortexau @g147  Naiceee. Let me sit on this for a while. You rock!

**Comment by dogancanbakir** [comment]
Decided to disable them as default and excluded them from tests

**Comment by dogancanbakir** [comment]
Hi @g147,  testing the sources and noticed subdomain.center returns an empty result every time. I tried different domains but had no luck. Could you take a look at it?

**Comment by g147** [comment]
Hey @dogancanbakir, yes it's normal behaviour. That API serves over 200-220k requests every hour, when that threshold crosses the load balancers do that until requests are back to normal to ensure better uptime for paid users. But no worries, I'll increase that threshold for time being. It should be back anytime within an hour.

**Comment by dogancanbakir** [comment]
I don't mean to point fingers, but don't you think that if free users struggle with it on their first attempt—especially during the times you mentioned—they might question its value? I do, for example, right now. We're always looking to integrate the sources that'll add value to the subfinder, thus empowering its users.

**Comment by g147** [comment]
Yes absolutely. You're right. We are working towards moving on from this strategy. Hopefully before Christmas.

**Comment by g147** [comment]
Hello @dogancanbakir! 

We have made the necessary modifications to ensure free users don't have to struggle anymore. 
I hope that helps.

Thanks!

**Comment by dogancanbakir** [comment]
This is great, thanks for doing this!
