### ISSUE TITLE
Add Brave API

### ISSUE THREAD

**Issue by Bundy01** [projectdiscovery/subfinder#1442]
### Please describe your feature request:
What do you think about integrating the Brave Search API into this project?
If it's possible to integrate it, it could be interesting with its 2000 free requests/month.
https://brave.com/search/api

### Describe the use case of this feature:
This API could enrich the number of free sources with a decent number of requests.

**Comment by GeorginaReeder** [comment]
Thanks so much for your feature request @Bundy01 - we'll take a look into this!

**Comment by dogancanbakir** [comment]
@Bundy01 I'm interested in how you utilize Brave Search for this. Could you share your experience to guide us moving forward? Thanks!

**Comment by Bundy01** [comment]
Hi,

it was just a suggestion. If it's not possible to integrate this API into Subfinder, you can close this issue.

Sorry for the inconvenience.

**Comment by dogancanbakir** [comment]
To use the API, you must provide your CC details --making it hard to use. I tried implementing the web search, but the rate limit is too high. I'll just close this.
