### ISSUE TITLE
need dockerhub images auto build

### ISSUE THREAD

**Issue by blue-bird1** [projectdiscovery/subfinder#151]
## What's the problem (or question)?

dockerhub images not use  automated build
## Do you have an idea for a solution?

Rebuild one automated build dockerhub images
## How can we reproduce the issue?

1.docker pull subfinder/subfinder
2.found it is obsolete
3.
4.

## What are the running context details?

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`):
* Client OS (e.g. `Microsoft Windows 10`)
* Program version (see banner): 
* Relevant console output (if any):
* Exception traceback (if any):

**Comment by Ice3man543** [comment]
@janmasarik how would this be done! I would love some help on this issue!

**Comment by janmasarik** [comment]
I would love to help, but you should be the owner of the dockerhub account as people will put implicit trust to it, and I cannot help with this without access to the account.

The flow is described in https://docs.docker.com/docker-hub/builds/#tag-and-branch-builds is actually pretty straightforward. Just open an dockerhub account and follow the steps described.

E.g. for https://github.com/janmasarik/bucketsperm or https://github.com/janmasarik/resolvable/, I have it configured like this, as I like to keep versioned images based on Github release tags (not just latest): 
![image](https://user-images.githubusercontent.com/18024936/70246853-a762b600-1778-11ea-9d24-04b5865b0fa8.png)

**Comment by Ice3man543** [comment]
Hey @janmasarik, thanks for the quick reply. I'll implement it asap.

**Comment by Ice3man543** [comment]
Hey @janmasarik, just added the dockerhub integration. Check it out - [https://hub.docker.com/r/ice3man/subfinder](https://hub.docker.com/r/ice3man/subfinder)

**Comment by janmasarik** [comment]
Nice one 👍, ty!
