### ISSUE TITLE
[Question] Invalid URL

### ISSUE THREAD

**Issue by oldesec** [projectdiscovery/subfinder#160]
Hello.

When sub domain is collected by executing "subfinder", some invalid URLs are collected.

The first "." Is included.

My command line
```
./subfinder -d freelancer.com
```

Example)
```
.freelancer.com
.www.freelancer.com
```

Thanks.

**Comment by Ice3man543** [comment]
Hey, thanks for notifying. This will be fixed in the recent edition.

**Comment by Ice3man543** [comment]
Hey, this has been fixed in the latest edition!
