### ISSUE TITLE
Add ready to use builds like Appimages, exe, deb?

### ISSUE THREAD

**Issue by ghost** [projectdiscovery/subfinder#163]
## Do you have an idea for a solution?
Make .travis? Can I do this? Which CI system do you prefer?

**Comment by marataziat** [comment]
https://github.com/milo2012/pathbrute/blob/master/goreleaser.yml - for an example

**Comment by marataziat** [comment]
https://goreleaser.com/ you an use it! You just need to run:
```
goreleaser init
```
And configure some CI https://goreleaser.com/ci/

**Comment by Ice3man543** [comment]
Yeah, you can do this. And goreleaser is cool.

**Comment by marataziat** [comment]
Yeah, we just need to run `goreleaser` on travis and set your releases api token on your travis account and it will works!

**Comment by marataziat** [comment]
#164 Made it

**Comment by Ice3man543** [comment]
Working on it now! Thanks for notifying!

**Comment by Ice3man543** [comment]
Added prebuilt binaries, check them out at [https://github.com/projectdiscovery/subfinder/releases/tag/v2.0](https://github.com/projectdiscovery/subfinder/releases/tag/v2.0)
