### ISSUE TITLE
Failure to install properly

### ISSUE THREAD

**Issue by zhenyanhuhashi** [projectdiscovery/subfinder#165]
![image](https://user-images.githubusercontent.com/43715449/56428859-76ba3300-62f3-11e9-8d64-051a9d8fb852.png)

![image](https://user-images.githubusercontent.com/43715449/56428902-9b160f80-62f3-11e9-8b88-20a460b19345.png)

Failure to install properly
https://github.com/golang/dep/cmd/dep
have been deleted

**Comment by Ice3man543** [comment]
Hey,  afaik dep does exists! It maybe a problem with your network. Feel free to reopen this issue. Closing it as i wasn't able to reproduce the issue!
