### ISSUE TITLE
config.json remains empty

### ISSUE THREAD

**Issue by DannyCork** [projectdiscovery/subfinder#166]
## What's the problem (or question)?
Subfinder doesn't add a config to config.json . I tried with multiple sources, Shodan, Censys etc.. doesn't matter which one.

## Do you have an idea for a solution?
nope.

## How can we reproduce the issue?

`
$go run main.go --set-config ShodanAPIKey=xxx
===============================================
-=Subfinder v1.1.3 github.com/subfinder/subfinder
===============================================
Successfully configured ShodanAPIKey=>xxx
-> Missing "domain" argument 
Try './subfinder -h' for more information

 more config.json 
{
	"virustotalApikey": "",
	"passivetotalUsername": "",
	"passivetotalKey": "",
	"securitytrailsKey": "",
	"riddlerEmail": "",
	"riddlerPassword": "",
	"censysUsername": "",
	"censysSecret": "",
	"shodanApiKey": ""
}

`

* Installation method 
apt install golang
git clone https://github.com/subfinder/subfinder.git
go get github.com/subfinder/subfinder
go run main.go

* Client OS :Ubuntu
* Program version 1.3

**Comment by Ice3man543** [comment]
Hey, this should be fixed in the new version! Closing this now.
