### ISSUE TITLE
[Enhancement] Take last commoncrawl index

### ISSUE THREAD

**Issue by phackt** [projectdiscovery/subfinder#167]
Hello,  
  
It's more a suggestion than an issue. I have recently installed subfinder and as a passive source, i saw ```commoncrawl```.  
  
However, subfinder is requesting the following index:  ```http://index.commoncrawl.org/CC-MAIN-2017-43-index```. Last one is ```CC-MAIN-2019-18-index```. It could be great to find a way to automatically take the last one.  
  
I also have a look how to do this.  
  
Cheer,
Gabriel.

**Comment by Ice3man543** [comment]
Hi, this is a good point, it'll be added in the next update.

**Comment by Ice3man543** [comment]
Hi, this has been fixed. Please checkout the latest version of subfinder
