### ISSUE TITLE
riddlers api key ! 

### ISSUE THREAD

**Issue by m4udSec** [projectdiscovery/subfinder#182]
the register part of the website is disabled, so it appear to have been acquired by F-Secure, wich seems to have its own api,  one thing is certain, i wasn`t able to get anywhere near an riddlers api key, would there be an alternative path to get my hands in one of those keys ?

thanks for this awesome project !

**Comment by Ice3man543** [comment]
Hey, i am not sure how i can help with this issue. Riddler has been removed from the list of sources. Closing this issue now!
