### ISSUE TITLE
Adding package vendoring

### ISSUE THREAD

**Issue by ChrisDryden** [projectdiscovery/subfinder#185]
## What's the problem (or question)?
I'm trying to add Subfinder to Homebrew and one of the requirements for new formulas is that all go project dependencies need to be vendored 
https://github.com/Homebrew/homebrew-core/pull/47499

## Do you have an idea for a solution?
If you are interested in doing this I can make the PR to add a /vendor/ folder with the dependencies

**Comment by Ice3man543** [comment]
Hey, dep does exists in the repo. It is generally a bad idea to have /vendor folders in the repo. Not sure how to proceed here.

**Comment by ChrisDryden** [comment]
sweet, I added dep and it works

**Comment by Ice3man543** [comment]
Nice, that's really great!

**Comment by Ice3man543** [comment]
Closing this now as fixed. Feel free to reopen in case there is anything else!
