### ISSUE TITLE
panic: runtime error: index out of range [recovered]

### ISSUE THREAD

**Issue by nocomp** [projectdiscovery/subfinder#188]
hi,
thxx a lot for this great tool,
just gave it a try, no issues for the install, but got an error when tryin for the first time.
here are the logs, hope it ll help you
keep it up!!

 subfinder -d jet.com -v

Running Source: Ask
Running Source: Archive.is
Running Source: Baidu
Running Source: Bing
Running Source: Censys
Running Source: CertDB
Running Source: CertificateTransparency
Running Source: Certspotter
Running Source: Commoncrawl
Running Source: Crt.sh
Running Source: Dnsdb
Running Source: DNSDumpster
Running Source: DNSTable
Running Source: Dogpile
Running Source: Exalead
Running Source: Findsubdomains
Running Source: Googleter
Running Source: Hackertarget
Running Source: Ipv4Info
Running Source: PassiveTotal
Running Source: PTRArchive
Running Source: Securitytrails
Running Source: Shodan
Running Source: Sitedossier
Running Source: Threatcrowd
Running Source: ThreatMiner
Running Source: Virustotal
Running Source: WaybackArchive
Running Source: Yahoo

Running enumeration on jet.com

[THREATMINER] batman-api.jet.com
[THREATMINER] partner.jet.com
[THREATMINER] www.jet.com
[THREATMINER] merchant-api.jet.com
[THREATMINER] merchant.qa.jet.com
dnsdb: Unexpected return status 404

[Exalead] www.jet.com
[Exalead] partner.jet.com2019/12/05 20:08:22 panic while running job: runtime error: index out of range
panic: runtime error: index out of range [recovered]
	panic: interface conversion: interface {} is runtime.errorString, not string

goroutine 73 [running]:
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker.func1(0xc000188140)
	/home/nocomp/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:61 +0x1c9
panic(0x75e8a0, 0xa96a00)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/subfinder/subfinder/libsubfinder/sources/dnsdumpster.Query(0xc000150140, 0x2, 0x2, 0x6c7101, 0x101)
	/home/nocomp/go/src/github.com/subfinder/subfinder/libsubfinder/sources/dnsdumpster/dnsdumpster.go:61 +0x14a6
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker(0xc000092dc0, 0xc000188140)
	/home/nocomp/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:64 +0x6e
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).worker(0xc000092dc0, 0x6)
	/home/nocomp/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:78 +0xb3
created by github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).Run
	/home/nocomp/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:181 +0x7d

**Comment by Ice3man543** [comment]
Hey, kindly update the subfinder version you're using. Update instructions can be found in the readme. the latest is v2.0. I'd recommend you to try that!
