### ISSUE TITLE
censys API keys are printed to stdout

### ISSUE THREAD

**Issue by cybercdh** [projectdiscovery/subfinder#192]
It seems when providing an API key and Secret for censys, these are printed to stdout and would appear in any output log file:

			fmt.Printf("%s %s\n", session.Keys.CensysToken, session.Keys.CensysSecret)

**Comment by Ice3man543** [comment]
Hey, thanks for notifying! Somehow that escaped from the final phases. Fixing it now!

**Comment by Ice3man543** [comment]
Done, let me know if you face this again

**Comment by cybercdh** [comment]
wow - quick turnaround!! nice work. amazing project.
