### ISSUE TITLE
can‘t run in windows10

### ISSUE THREAD

**Issue by carryshen** [projectdiscovery/subfinder#198]
I've downloaded latest release subfinder-windows-amd64.exe.tar, but can't run subfinder-windows-amd64.exe because "the application is not able to run in your computer", the system is windows10, can you tell me how to deal with it, thank you.

**Comment by bauthard** [comment]
I can confirm the issue, got the following error on 64 bit machine `"subfinder-windows-amd64.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher."`

**Comment by bauthard** [comment]
@carryshen try with the latest release at https://github.com/projectdiscovery/subfinder/releases, working fine now.
