### ISSUE TITLE
[Request] Add the bruteforce module back in subfinder

### ISSUE THREAD

**Issue by bugbaba** [projectdiscovery/subfinder#201]
Hi :)

## What's the problem (or question)?
I have been using subfinder for bruteforcing subdomains, But in the recent update `2.0` bruteforce module has been removed from the subfinder.

## Do you have an idea for a solution?
The old bruteforce module is pretty robust so implementing that back would also work.

--
Regards,
bugbaba

**Comment by ehrishirajsharma** [comment]
Thanks for the feedback.

We actually wanted to focus subfinder solely for passive enumeration, this would allow us to work dedicatedly on a specific solution and improve it by time. We are planning to open-source a separate tool for active enumeration, will post comment once its out.
