### ISSUE TITLE
[Feature Request] Add option to show the version

### ISSUE THREAD

**Issue by riramar** [projectdiscovery/subfinder#204]
Could you please consider to include an option to show the version of subfinder?
This would help quick identify the actual version and check if there is a need to upgrade.

**Comment by Ice3man543** [comment]
@riramar, nice idea. I'll add it asap! Thanks

**Comment by Ice3man543** [comment]
Hey @riramar, this feature was added in #212. Closing this issue now!

**Comment by riramar** [comment]
Thanks!
