### ISSUE TITLE
subfinder should not download itself into ./vendor directory

### ISSUE THREAD

**Issue by blshkv** [projectdiscovery/subfinder#217]
I'm not a Go expect and not sure what's going on here.
subfinder downloads itself (subfinder@v2.3.1+incompatible as of now) and requires itself for compilation.

I use the following method to confirm it:

git clone https://github.com/projectdiscovery/subfinder.git
cd subfinder
go mod init subfinder  (migrate to modules)
go mod vendor

The last command would download the following list of packages:
```
<skip>
go: finding github.com/projectdiscovery/subfinder v2.3.1+incompatible
go: downloading github.com/projectdiscovery/subfinder v2.3.1+incompatible
go: extracting github.com/projectdiscovery/subfinder v2.3.1+incompatible
<skip>
```

You can also confirm it by inspecting ```vendor``` directory or using the following command:
```
bash$ go list -m all | grep subfinder
subfinder
github.com/projectdiscovery/subfinder v2.3.1+incompatible
```

```
bash$ go mod why -m github.com/projectdiscovery/subfinder
# github.com/projectdiscovery/subfinder
subfinder/cmd/subfinder
github.com/projectdiscovery/subfinder/pkg/log
```

**Comment by Ice3man543** [comment]
Hey @blshkv, go modules are not yet used by subfinder so as to not break stuff that depends on the dep dependency manager. We'll soon migrate to it. Till then you should use the standard way to install which is  - 

```
go get -u -v github.com/projectdiscovery/subfinder
```

Thanks!

**Comment by blshkv** [comment]
I'm packaging subfinder for Pentoo linux and can't use "go get".
We need to download all dependencies in advance and compile it using "go build".
I find that the easiest way to get the list of dependencies is to convert to modules.

The final ebuild is here https://github.com/pentoo/pentoo-overlay/commit/d2ab6a30046b46974142244440ea15a1c6ed589 just in case if you are curios.

**Comment by blshkv** [comment]
btw, I have tried "go get -v github.com/projectdiscovery/subfinder/cmd/subfinder" from cli, it still gets ``~/go/pkg/mod/cache/download/github.com/projectdiscovery/subfinder/@v/v2.3.1+incompatible.zip```

so it looks like there is no difference in these two methods.
