### ISSUE TITLE
Using psql for crt.sh subdomain enumeration

### ISSUE THREAD

**Issue by mpgn** [projectdiscovery/subfinder#218]
## What's the problem ?
Actually, subfinder use a simple GET request to get subdomain from crt.sh. This technique is simple but it can miss lot of subomain.

## Do you have an idea for a solution?
Solution: use the progresql database of crt.sh (open to everyone). Script example :

```sh
#!/bin/sh

query="SELECT ci.NAME_VALUE NAME_VALUE FROM certificate_identity ci WHERE reverse(lower(ci.NAME_VALUE)) LIKE reverse(lower('%.$1'));"
(echo $1; echo $query | \
    psql -t -h crt.sh -p 5432 -U guest certwatch | \
    sed -e 's:^ *::g' -e 's:^*\.::g' -e '/^$/d' | \
    sed -e 's:*.::g';) | sort -u
```

## How can we reproduce the issue?

subfinder output:

![image](https://user-images.githubusercontent.com/5891788/73156896-8fa41000-40df-11ea-829d-0af920df8a22.png)

PSQL output
![image](https://user-images.githubusercontent.com/5891788/73156910-9cc0ff00-40df-11ea-8f2a-89050d54cac8.png)

**Comment by Ice3man543** [comment]
Hey @mpgn, thanks for this issue. This is curious, i thought both had same reults. Anyway, thanks for notifying! I'll working on adding this asap.

**Comment by Edu4rdSHL** [comment]
@mpgn try Findomain while it's fixed. It query the crtsh database directly and if it isn't success then uses the API method.

**Comment by Ice3man543** [comment]
@mpgn, @Edu4rdSHL this should be fixed as of now. If the db interface doesn't works, we fallback on http. Thanks for creating the issue and helping with this addition!

**Comment by mpgn** [comment]
Nice @Ice3man543 ! good work
