### ISSUE TITLE
Discover RSS feeds

### ISSUE THREAD

**Issue by sojusnik** [projectdiscovery/subfinder#219]
I wonder if subfinder would be able to detect RSS feeds on sites where they are not promoted, but nevertheless present?

Let's take f.i. [eurailpress.de](https://www.eurailpress.de/). Neither on the main page, nor its source code you'll find a valid feed, but after a lot of trial and error you could stumble upon the proper feed address: https://www.eurailpress.de/news/rss.xml

Is subfinder capable of automating this process?
If yes, is there a step-by-step tutorial?
If not, do you know ways to do so?

**Comment by bauthard** [comment]
Hi @sojusnik, 

The purpose of `subfinder` is to find **subdomains** of the given domain, finding specific files is not in the scope of subfinder.
