### ISSUE TITLE
not working behind proxy

### ISSUE THREAD

**Issue by darkweb-123** [projectdiscovery/subfinder#226]
## How can we reproduce the issue?

1.
2.
3.
4.

## What are the running context details?

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`):
* Client OS (e.g. `Microsoft Windows 10`)
* Program version (see banner): 
* Relevant console output (if any):
* Exception traceback (if any):

**Comment by bauthard** [comment]
Hi @darkweb-123, 

Can you elaborate on the problem in detail? how to reproduce this issue.

**Comment by SandeepkrishnaS** [comment]
I think I have the same problem. I am sitting behind my institute's proxy server. Only outgoing http(s) traffic is allowed. Can proxy configuration be set for subfinder??

**Comment by bauthard** [comment]
Hi @darkweb-123 @SandeepkrishnaS, 

You can try with default proxy support. 

```
HTTP_PROXY=http://127.0.0.1:8080 subfinder -d test.com
```

Replace `127.0.0.1:8080` with the proxy you want.

**Comment by bauthard** [comment]
Closing this as this is out of the scope of the SubFinder, a possible workaround is shared in the above comment.

**Comment by riisi** [comment]
Just a note that in my testing, subfinder doesn't seem to respect the HTTP_PROXY variable.

**Comment by tallona** [comment]
I second that, subfinder doesn't seem to take HTTP_PROXY into account. Have tried a few things but nothing works to get subfinder to use the proxy.
