### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by root0er** [projectdiscovery/subfinder#228]
The application crashes with some domains
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7bdc40]

goroutine 37485 [running]:
github.com/m-mizutani/urlscan-go/urlscan.Client.post(0xc000026330, 0x24, 0x9a3bd3, 0x19, 0x99994e, 0x4, 0x945d60, 0xc00101b020, 0x8c1360, 0xc0000e8a80, ...)
	/home/root0er/go/src/github.com/m-mizutani/urlscan-go/urlscan/client.go:76 +0xa20
github.com/m-mizutani/urlscan-go/urlscan.(*Client).Submit(0xc00043e060, 0xc000baf300, 0x17, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/root0er/go/src/github.com/m-mizutani/urlscan-go/urlscan/scan.go:39 +0x16d
github.com/projectdiscovery/subfinder/pkg/subscraping/sources/urlscan.(*Source).Run.func1(0xc000f32e70, 0xc00002fd40, 0xc000e38000, 0xf, 0xdd1840)
	/home/root0er/go/src/github.com/projectdiscovery/subfinder/pkg/subscraping/sources/urlscan/urlscan.go:26 +0x1c5
created by github.com/projectdiscovery/subfinder/pkg/subscraping/sources/urlscan.(*Source).Run
	/home/root0er/go/src/github.com/projectdiscovery/subfinder/pkg/subscraping/sources/urlscan/urlscan.go:19 +0x89
`

this is my versionof go:go version go1.13.3 linux/amd64

**Comment by lc** [comment]
Hey all,

This appears to be an issue with the urlscan-go library, I've found and fixed the issue. You can see the status of the PR here: https://github.com/m-mizutani/urlscan-go/pull/2

**Comment by lc** [comment]
@Mzack9999,

This issue has been fixed, the PR has been merged: m-mizutani/urlscan-go#2.

**Comment by Mzack9999** [comment]
Thanks for your work @lc!

@root0er let us know if you still have any issue. Closing as this should be fixed.
