### ISSUE TITLE
crt.sh source replacing wildcard/asterisk (*) with 'n' in the results

### ISSUE THREAD

**Issue by h121h** [projectdiscovery/subfinder#230]
## What's the problem (or question)?
The CRTSH source is appending "n" in front of several of the results (subdomains) because of the wildcard/asterisk being returned in the results.

## How can we reproduce the issue?
1. Run this command: ./subfinder -nC -d google.com -sources crtsh
2. Observe several of the results have "n" appended in place of the wildcards/asterisks (*) in the results (subdomains).

## What are the running context details?

Installation method: Cloned git repo; built from source.
Client OS:
Linux crpkli01 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux
Debian GNU/Linux 10

Program version (see banner): v2
Relevant console output (if any):

`#./subfinder -nC -d google.com -sources crtsh

        _     __ _         _
____  _| |__ / _(_)_ _  __| |___ _ _
(_-< || | '_ \  _| | ' \/ _  / -_) '_|
/__/\_,_|_.__/_| |_|_||_\__,_\___|_| v2

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[WRN] By using subfinder, you also agree to the terms of the APIs used.

[INF] Enumerating subdomains for google.com
docs.google.com
**nmail.google.com**
**nplus.google.com**
**nsites.google.com**
**ntalkgadget.google.com**
onex.wifi.google.com
accounts.google.com
hosted-id.google.com
adwords.google.com
**nadwords.google.com**
vp.video.l.google.com
wifi.google.com
jmt0.google.com
**nupload.video.google.com**
eggroll.ext.google.com
`

**Comment by bauthard** [comment]
```
root@b0x:~# subfinder -nC -d google.com -sources crtsh

        _     __ _         _         
____  _| |__ / _(_)_ _  __| |___ _ _ 
(_-< || | '_ \  _| | ' \/ _  / -_) '_|
/__/\_,_|_.__/_| |_|_||_\__,_\___|_| v2

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[WRN] By using subfinder, you also agree to the terms of the APIs used.

[INF] Enumerating subdomains for google.com
14th-154-color.corp.google.com
14th-154-color.printer.corp.google.com
14thstreetsteve-color.corp.google.com
14thstreetsteve-color.printer.corp.google.com
15-love-color.corp.google.com
15-love-color.printer.corp.google.com
1integrate-dev.vm.corp.google.com
```

```
root@b0x:~# subfinder -version

        _     __ _         _         
____  _| |__ / _(_)_ _  __| |___ _ _ 
(_-< || | '_ \  _| | ' \/ _  / -_) '_|
/__/\_,_|_.__/_| |_|_||_\__,_\___|_| v2

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[WRN] By using subfinder, you also agree to the terms of the APIs used.

[INF] Current Version: 2.3.2
```

@h121h make sure you are running on the latest version, I'm not able to reproduce this on my side.

**Comment by h121h** [comment]
> ```
> root@b0x:~# subfinder -nC -d google.com -sources crtsh
> 
>         _     __ _         _         
> ____  _| |__ / _(_)_ _  __| |___ _ _ 
> (_-< || | '_ \  _| | ' \/ _  / -_) '_|
> /__/\_,_|_.__/_| |_|_||_\__,_\___|_| v2
> 
> 		projectdiscovery.io
> 
> [WRN] Use with caution. You are responsible for your actions
> [WRN] Developers assume no liability and are not responsible for any misuse or damage.
> [WRN] By using subfinder, you also agree to the terms of the APIs used.
> 
> [INF] Enumerating subdomains for google.com
> 14th-154-color.corp.google.com
> 14th-154-color.printer.corp.google.com
> 14thstreetsteve-color.corp.google.com
> 14thstreetsteve-color.printer.corp.google.com
> 15-love-color.corp.google.com
> 15-love-color.printer.corp.google.com
> 1integrate-dev.vm.corp.google.com
> ```
> 
> ```
> root@b0x:~# subfinder -version
> 
>         _     __ _         _         
> ____  _| |__ / _(_)_ _  __| |___ _ _ 
> (_-< || | '_ \  _| | ' \/ _  / -_) '_|
> /__/\_,_|_.__/_| |_|_||_\__,_\___|_| v2
> 
> 		projectdiscovery.io
> 
> [WRN] Use with caution. You are responsible for your actions
> [WRN] Developers assume no liability and are not responsible for any misuse or damage.
> [WRN] By using subfinder, you also agree to the terms of the APIs used.
> 
> [INF] Current Version: 2.3.2
> ```
> 
> @h121h make sure you are running on the latest version, I'm not able to reproduce this on my side.

Thanks @bauthard - You are correct. I was running an older version. This is not reproducible in version 2.3.2.

**Comment by bauthard** [comment]
Thank you for confirming this @h121h
