### ISSUE TITLE
Flag to not resolve hosts

### ISSUE THREAD

**Issue by c0rvax** [projectdiscovery/subfinder#233]
Hey dudes!

I think the tool lacks a flag to not resolve any domains. That would be handy in people's tools as regularly they do have their own resolvers. 

Could you point me to a flag (if there is one) or add a new one to support this functionality?

Thanks!

**Comment by bauthard** [comment]
Hi @c0rvax, 

on default run it does not resolve anything, you only see the passive results, do you have any examples?

**Comment by c0rvax** [comment]
Oh, if so, then it is good enough. I read the documentation and though that by default it uses `subfinder -r 1.1.1.1,1.0.0.1` to resolve the hostnames received.

Thanks
