### ISSUE TITLE
Flag to upload found subdomains in the dataset 

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/subfinder#234]
## Do you have an idea for a solution?
Updating found subdomain to the dataset so later we can query them on the go. 

## What are the running context details?

```
subfinder -d example.com -cd
```

`-cd` this flag to update data to [Chaos dataset](https://chaos.projectdiscovery.io/). 

We can make use of `config.yml` file to store the `chaos-key`

**Comment by Mzack9999** [comment]
Implemented in #238
