### ISSUE TITLE
[WRN] Could not run source urlscan: Fail to get result query

### ISSUE THREAD

**Issue by ddervosj** [projectdiscovery/subfinder#235]
Hello,

Post update to 2.3.3 using go get -v -u ... I'm receiving below error when running the tool against any domain:

[WRN] Could not run source urlscan: Fail to get result query: Fail to unmarshal urlscan.io get result: json: cannot unmarshal number into Go struct field .meta.processors.wappa.data.categories.priority of type string

[INF] Current Version: 2.3.3

Any idea what may be causing this?

**Comment by Mzack9999** [comment]
Hi @ddervosj 

I suppose this shares the same root cause of #228 - Hopefully the PR with the fix to the original library will also address this.

**Comment by Mzack9999** [comment]
@ddervosj This should have been solved in https://github.com/m-mizutani/urlscan-go/pull/2
Let us know if you still experience any issue

**Comment by ddervosj** [comment]
Yep - error has been fixed. However not seeing any additional subdomains being pulled by urlscan.. Gonna keep trying lol
