### ISSUE TITLE
valid 

### ISSUE THREAD

**Issue by scottishhunter1** [projectdiscovery/subfinder#244]
certspotter:  
	- sadasdasd27512315asd_P7VbIasdd123asdnX7decDI329lasdasgGY4J 

is This pattern of api key valid are not

**Comment by bauthard** [comment]
Yes, here is an example @scottishhunter1 
```
certspotter: 
  - key_here
```

also, you can confirm by running:- 

```
root@test:~# subfinder -d hackerone.com -sources certspotter -silent 
www.hackerone.com
api.hackerone.com
mta-sts.managed.hackerone.com
mta-sts.hackerone.com
mta-sts.forwarding.hackerone.com
support.hackerone.com
docs.hackerone.com
```

**Comment by scottishhunter1** [comment]
i tried but didn,t work

**Comment by bauthard** [comment]
I've updated the example config file [here](https://github.com/projectdiscovery/subfinder/blob/master/config.yaml) which is working on my side.
