### ISSUE TITLE
improvements with json output format 

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/subfinder#245]
## What's the problem (or question)?
1. JSON output is not supported in passive mode. 

```
root@b0x:~# subfinder -silent -d hackerone.com -oJ
[FTL] Program exiting: JSON flag must be used with RemoveWildcard option
```

2. JSON output does not include source information of found subdomain 

```
root@b0x:~# cat test.json 
{"host":"docs.hackerone.com","ip":"185.199.110.153"}
{"host":"www.hackerone.com","ip":"104.16.99.52"}
{"host":"hackerone.com","ip":"104.16.100.52"}
```

3. stdout does not prints `json` format even with `oJ` flag. 

```
root@b0x:~# subfinder -silent -d hackerone.com -oJ -nW -o test.json -sources crtsh 
api.hackerone.com
docs.hackerone.com
go.hackerone.com
hackerone.com
info.hackerone.com
```

## Do you have an idea for a solution?
- [x] Make the `json` output optional instead of using only with `nW` flag. 
- [x] Include `source` information in the `json` output.

```
{"host":"docs.hackerone.com","ip":"185.199.110.153", "source":"crtsh"}
{"host":"www.hackerone.com","ip":"104.16.99.52", "source":"securitytrails"}
{"host":"test.hackerone.com","ip":"", "source":"crtsh"}
```
- [x] `json` stdout, same as https://github.com/projectdiscovery/naabu/issues/32 fix. 
- [x] adding `-json` flag for json output format to align with other tools https://github.com/projectdiscovery/naabu/issues/32

**Note:- we will still support `oJ` flag at the code level to makes it backward compatible.**

**Comment by vzamanillo** [comment]
Can we close this?

**Comment by bauthard** [comment]
This one added here projectdiscovery#245, @vzamanillo sure.
