### ISSUE TITLE
Improved error handling 

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/subfinder#246]
## What's the problem (or question)?

It looks like 4xx/5xx status codes and dnsdumpster/hackertarget rate limits are still being ignored. Robust error handling is pretty important

Source:- https://github.com/projectdiscovery/subfinder/pull/220#issuecomment-639328629

**Comment by vzamanillo** [comment]
Should we just handle unexpected errors on those two sources or do we need to do something generic that reports error when it is not a 200 status code (return error from agent methods)?

**Comment by Ice3man543** [comment]
@vzamanillo  I think generic errors should be the way to go since it takes way too much time to go through each source identifying their error codes. A wrapper that returns the status code and a log message should be enough.

**Comment by bauthard** [comment]
Fixed with https://github.com/projectdiscovery/subfinder/pull/274
