### ISSUE TITLE
go/src/github.com/projectdiscovery/subfinder/pkg/subscraping/agent.go:37:14: undefined: http.NewRequestWithContext

### ISSUE THREAD

**Issue by itachisec** [projectdiscovery/subfinder#249]
## How can we reproduce the issue?

1.
2.
3.
4.

## What are the running context details?

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`):
* Client OS (e.g. `Microsoft Windows 10`)
* Program version (see banner): 
* Relevant console output (if any):
* Exception traceback (if any):

**Comment by itachisec** [comment]
I have golang 14.4(newest) when i try to download it threw go get or git clone or wget tar file all responsives are go/src/github.com/projectdiscovery/subfinder/pkg/subscraping/agent.go:37:14: undefined: http.NewRequestWithContext

**Comment by bauthard** [comment]
Hey @itachisec, 

Can you please share a screenshot with version details:- 

```bash
> go version
```

**Comment by itachisec** [comment]
Hey @bauthard,

Thank your already in advance for the quick responce!

My go version is 1.14.4
![image](https://user-images.githubusercontent.com/62624280/85220449-c5f26c80-b3ab-11ea-9990-2d2bdd85584c.png)

Also tried it with lower versions.

I download it with the GO GET, WGET TAR and GITclone unpack, all the same error. Pretty frustrating because this is my number one choice tool for sub scraping.

Much thanks in advance <3

**Comment by Ice3man543** [comment]
Hey, this should not be happening with the binary version. Can you share steps you followed or commands you ran so that we can reproduce them?

**Comment by itachisec** [comment]
Hi @Ice3man543 

The following steps is what I do:

1: wget https://dl.google.com/go/go1.14.4.linux-amd64.tar.gz
2: sudo tar -C /usr/local/ -xzf go1.14.4.linux-amd64.tar.gz
3: echo 'export GOROOT=/usr/local/go' >> ~/.bashrc
echo 'export GOPATH=$HOME/go' >> ~/.bashrc
echo 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH' >> ~/.bashrc
source .bashrc

4: GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/cmd/subfinder


Its on a VPS digital ocean UBUNTU.

Again, thank your for the quick reply and much thanks in advance.

**Comment by itachisec** [comment]
@bauthard @Ice3man543 any idea's?

**Comment by bauthard** [comment]
Hey @itachisec, 

It's an issue with your go installation path which somehow picks the old version during installation, so either you can fix that with a google search or you can simply download the binary file to use it directly from here https://github.com/projectdiscovery/subfinder/releases

After downloading the file:- 

```
tar -xzvf subfinder-linux-amd64.tar.gz
mv subfinder /usr/bin/subfinder
subfinder 
```

**Comment by itachisec** [comment]
Oke ty very very much

Op ma 22 jun. 2020 12:56 schreef bauthard <notifications@github.com>:

**Comment by srivastava007** [comment]
simple download previous version of the file...it is working as of now
