### ISSUE TITLE
Release 2.3.5 on Linux (amd64) - 'No such file or directory'

### ISSUE THREAD

**Issue by cramppet** [projectdiscovery/subfinder#251]
# Description

When running `./subfinder` from the command line, the program fails to start and the shell reports `No such file or directory`.

I used the latest release binary (2.3.5) and was running from a fresh virtual machine (Ubuntu 18.04.3; amd64)

I previously used version 2.3.4 and I don't recall experiencing this issue.

# Potential fix/workaround

I probed the problem further by running `ldd subfinder` which reported:

```
linux-vdso.so.1 (0x00007ffdb97f7000)
libc.musl-x86_64.so.1 => not found   
```

This lead to a [potentially related issue report](https://github.com/alexander-akhmetov/python-telegram/issues/3) that I used to solve the problem:

```
apt-get install musl-dev
```

And then

```
ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1
```

**Comment by bauthard** [comment]
@cramppet This is fixed in latest release https://github.com/projectdiscovery/subfinder/releases/tag/v2.3.6
