### ISSUE TITLE
Too many files open error

### ISSUE THREAD

**Issue by derrickjudge** [projectdiscovery/subfinder#252]
## What's the problem (or question)?
Too many open file error:

[ERR] Could not create file subfinder.json for notmysite.net: open subfinder.json: too many open files
[FTL] Could not run enumeration: open subfinder.json: too many open files
✘-1 ~/cloned_repos/subfinder/tar [master|…7]
13:00 $ ls
LICENSE				domainlist.txt			subfinder.json			tmp.json
README.md			subfinder			subfinder_2.3.5_macOS_amd64.tar
✔ ~/cloned_repos/subfinder/tar [master|…7]
13:01 $ ulimit
unlimited
13:07 $ ulimit -u
2784

## Do you have an idea for a solution?
Set ulimit for user or process (especially when using a domain list)

## How can we reproduce the issue?
./subfinder -dL ./domainlist.txt -o subfinder.json -oJ -nW -r 8.8.8.8
scan a large number of domains or set artificially low ulimit 

## What are the running context details?

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`):
tar.gz
* Client OS (e.g. `Microsoft Windows 10`)
OSX
* Program version (see banner): 
2.3.5
* Relevant console output (if any):
[ERR] Could not create file subfinder.json for notmysite.net: open subfinder.json: too many open files
[FTL] Could not run enumeration: open subfinder.json: too many open files
✘-1 ~/cloned_repos/subfinder/tar [master|…7]
13:00 $ ls
LICENSE				domainlist.txt			subfinder.json			tmp.json
README.md			subfinder			subfinder_2.3.5_macOS_amd64.tar
✔ ~/cloned_repos/subfinder/tar [master|…7]
13:01 $ ulimit
unlimited
13:07 $ ulimit -u
2784
* Exception traceback (if any):

**Comment by bauthard** [comment]
Hey thanks for the detailed issue, this is already being tracked here https://github.com/projectdiscovery/subfinder/issues/250
