### ISSUE TITLE
support

### ISSUE THREAD

**Issue by chawdamrunal** [projectdiscovery/subfinder#258]
subfinder -d onurair.com -silent | httpx-silent | > outputttt
bash: httpx-silent: command not found

could you help to solve this

**Comment by bauthard** [comment]
Hey, I'm assuming you have `httpx` installed on your system, and thr is space between httpx and silent, `-silent` is flag used along with `httpx`, working command would be:- 

```
subfinder -d onurair.com -silent | httpx -silent -o output.txt
```
