### ISSUE TITLE
Github Rate Limit

### ISSUE THREAD

**Issue by SimoneBovi** [projectdiscovery/subfinder#262]
Hi,
as Github is rate limiting requests, I would advise to repeat the new Github recon process around 4-5 times, as suggested by Jason Haddix, with some different sleep time.

Thanks!

**Comment by bauthard** [comment]
@SimoneBovi Thank you for creating this issue, can you please share the error details how it looks like while running subfinder? 

@vzamanillo do you think adding multiple key support will solve this or more sleep in case the rate limit occurs?

**Comment by SimoneBovi** [comment]
@bauthard I do not receive any error. However Github is rate limited so subfinder would likely says OK while github is finding nothing.
For me a sleep is better than multiple key support so to avoid creating more, but this is your choice :) 

Thanks!

**Comment by vzamanillo** [comment]
Hey, I think multiple key support will be better because it doesn't affect to speed, it should be easy to implement picking a random key from the list.

**Comment by bauthard** [comment]
@vzamanillo sure, few things to consider, in many cases it's possible users have a single key and can not maintain many, in that case, they are bound to get rate limit, so it would be better if we can slow down the request when rate limit gets hits and user don't have additional keys in config. 

so the flow can be like this! 

in case users have a single key and got rate limit error, slow down the request based on Github specification, or switch to another key for the next request in case users have more keys in the config file, do you think this strategy will be good?

Multiple keys can be submitted lik this:- 

```
github:
  - <token-1> 
  - <token-2> 
  - <token-3> 
  - <token-4> 
  - <token-5>

**Comment by vzamanillo** [comment]
Looks good to me!

**Comment by vzamanillo** [comment]
This is in progress, and... a new surprise to incredibly speed up the search results using `text-match-metadata`.

https://docs.github.com/en/rest/reference/search#text-match-metadata

**Comment by vzamanillo** [comment]
I am working on a new method to get the subdomains using the GitHub search `text-match-metadata` but I think it is better to try it on another branch so as not to mix changes, I will add a new PR after it validates and merges this one.
