### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by shafan** [projectdiscovery/subfinder#263]
When I want to update the module with the command :
`GO111MODULE=on go get -u -v github.com/projectdiscovery/subfinder/cmd/subfinder`
it's not working.

Here's the message that appears:
`go: found github.com/projectdiscovery/subfinder/cmd/subfinder in github.com/projectdiscovery/subfinder v2.3.4+incompatible`

this is complete message : 
`go: found github.com/projectdiscovery/subfinder/cmd/subfinder in github.com/projectdiscovery/subfinder v2.3.4+incompatible
go: finding module for package github.com/projectdiscovery/gologger
go: finding module for package github.com/pkg/errors
go: finding module for package github.com/json-iterator/go
go: finding module for package gopkg.in/yaml.v3
go: finding module for package github.com/lib/pq
go: finding module for package github.com/m-mizutani/urlscan-go/urlscan
go: finding module for package github.com/miekg/dns
go: finding module for package github.com/rs/xid
go: found github.com/projectdiscovery/gologger in github.com/projectdiscovery/gologger v1.0.0
go: found github.com/json-iterator/go in github.com/json-iterator/go v1.1.10
go: found github.com/pkg/errors in github.com/pkg/errors v0.9.1
go: found gopkg.in/yaml.v3 in gopkg.in/yaml.v3 v3.0.0-20200615113413-eeeca48fe776
go: found github.com/miekg/dns in github.com/miekg/dns v1.1.30
go: found github.com/rs/xid in github.com/rs/xid v1.2.1
go: found github.com/lib/pq in github.com/lib/pq v1.7.0
go: found github.com/m-mizutani/urlscan-go/urlscan in github.com/m-mizutani/urlscan-go v1.0.0
go: github.com/konsorten/go-windows-terminal-sequences upgrade => v1.0.3
go: github.com/modern-go/reflect2 upgrade => v1.0.1
go: github.com/pkg/errors upgrade => v0.9.1
go: github.com/sirupsen/logrus upgrade => v1.6.0
go: github.com/logrusorgru/aurora upgrade => v2.0.3+incompatible
go: github.com/modern-go/concurrent upgrade => v0.0.0-20180306012644-bacd9c7ef1dd
go: golang.org/x/net upgrade => v0.0.0-20200707034311-ab3426394381
go: golang.org/x/crypto upgrade => v0.0.0-20200709230013-948cd5f35899
go: golang.org/x/sys upgrade => v0.0.0-20200625212154-ddb9806d33ae`

An idea ?
thanks

**Comment by bauthard** [comment]
Hi @shafan, 

Thank you for creating this issue, we will investigate this, in case you want to update now, either you can delete old subfinder and download it again, or download the latest binary.

**Comment by vzamanillo** [comment]
@shafan As a temporal workaround you can update the package with the following command:

`GO111MODULE=auto go get -u -v github.com/projectdiscovery/subfinder/cmd/subfinder`

Refs:
- https://github.com/golang/go/issues/28309
- https://github.com/golang/go/issues/31857

**Comment by bauthard** [comment]
Hi @shafan, 

Can you try this again? looks fixed to me.

**Comment by bauthard** [comment]
I've confirmed this, 

```
GO111MODULE=auto go get -u -v github.com/projectdiscovery/subfinder/cmd/subfinder
```

This works well to update on the latest version on fresh box, closing this issue now.
