### ISSUE TITLE
urlscan source is not working properly

### ISSUE THREAD

**Issue by wanted1205** [projectdiscovery/subfinder#266]
## What's the problem (or question)?
[WRN] Could not run source urlscan: Fail to get result query: Fail to unmarshal urlscan.io get result: json: cannot unmarshal number into Go struct field .meta.processors.wappa.data.categories.priority of type string
[WRN] Could not run source spyse: readObjectStart: expect { or n, but found <, error found in #1 byte of ...|<html>
<he|..., bigger context ...|<html>
<head><title>404 Not Found</title></head>
|...
[WRN] Could not run source virustotal: EOF
[WRN] Could not run source commoncrawl: []commoncrawl.indexResponse: decode slice: expect [ or n, but found <, error found in #1 byte of ...|<html>
<he|..., bigger context ...|<html>
<head><title>502 Bad Gateway</title></head>|...

Why is this happenning

**Comment by bauthard** [comment]
Can you add more details to this issue @wanted1205, what cmd you used? do you have `urlscan` key saved in your config file or anymore more to share? 


what version of subfinder you are using?

**Comment by wanted1205** [comment]
Yes I added all the required keys then also issue perists

**Comment by vzamanillo** [comment]
@wanted1205 Looking at the error message, I think your problem is not directly related with `urlscan` source because `spyse`, `virustotal`, `commoncrawl`... are failing too, maybe is related to a network problem, are you behind a proxy or firewall?

**Comment by wanted1205** [comment]
Well i have nice internet connection and also i am not behind any firewall or proxy

**Comment by bauthard** [comment]
Looks like an issue, following error using valid key from https://urlscan.io/user/profile/

```bash
> subfinder -d hackerone.com -sources urlscan -v

[WRN] Could not run source urlscan: Fail to get result query: Fail to unmarshal urlscan.io get result: json: cannot unmarshal number into Go struct field .meta.processors.wappa.data.categories.priority of type string
```
