### ISSUE TITLE
Upgrading from 2.3.5 to 2.3.6 is actually downgrading to 2.3.4

### ISSUE THREAD

**Issue by riramar** [projectdiscovery/subfinder#268]
## What's the problem (or question)?
Upgrading from 2.3.5 to 2.3.6 is actually downgrading to 2.3.4

## Do you have an idea for a solution?
No idea.

## How can we reproduce the issue?
1. Install 2.3.5
2. Run GO111MODULE=on go get -u -v github.com/projectdiscovery/subfinder/cmd/subfinder
3. Check the version
4. [INF] Current Version: 2.3.4

## What are the running context details?
* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`):
GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/cmd/subfinder

* Client OS (e.g. `Microsoft Windows 10`)
Kali and Ubuntu latest versions

* Program version (see banner): 
```
ricardo@zion:~$ subfinder --version

        _     __ _         _         
____  _| |__ / _(_)_ _  __| |___ _ _ 
(_-< || | '_ \  _| | ' \/ _  / -_) '_|
/__/\_,_|_.__/_| |_|_||_\__,_\___|_| v2

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[WRN] By using subfinder, you also agree to the terms of the APIs used.

[INF] Current Version: 2.3.4
```

* Relevant console output (if any):
* Exception traceback (if any):

**Comment by bauthard** [comment]
- Go Modules need to be updated in order to fix this.

**Comment by riramar** [comment]
By removing "GO111MODULE" from the upgrade command I was able to upgrade to the latest version.
