### ISSUE TITLE
Add golangci-lint-action to the existing GitHub workflow

### ISSUE THREAD

**Issue by vzamanillo** [projectdiscovery/subfinder#277]
[golangci-lint-action](https://github.com/golangci/golangci-lint-action) It's the official GitHub action for `golangci-lint` from it's authors. The action runs `golangci-lint` and reports issues from linters.

[golangci-lint](https://github.com/golangci/golangci-lint) is a fast Go linters runner. It runs linters in parallel, uses caching, supports yaml config, has integrations with all major IDE and has dozens of linters included.

Including this action into the workflow would increment the project code quality and could prevent possible future leaks and/or failures setting a minimum of checks and rules, I think it could be very favorable.

A list of available linters on the [official documentation](https://golangci-lint.run/usage/linters/)

If we adopt this standard, we would have to first try a local installation, run the chosen linters and correct the errors to adjust the source code and establish a new starting point. We cannot adopt it without making the corrections first because it would make it difficult uploading new pull requests to collaborators.

Any thoughts?

**Comment by vzamanillo** [comment]
I have mentioned `golangci-lint-action` because it is very versatile and offers the possibility to use various linters for different things, but any other mechanism to improve the quality of the code would be just as good.

**Comment by Ice3man543** [comment]
@vzamanillo Hey, thanks for your contributions to the project! The work you've been doing is really amazing. Regarding `golangci-lint`, it's a very good idea. Let's add this to this as well as other open source projects we have. This was something we had to do however not been able to yet due to time constraints.

**Comment by vzamanillo** [comment]
Hey @Ice3man543!

Thank you very much! I am glad to do this.

Ok let's do it!

So that the development does not have any negative impact on the current repository, I will try to test locally using https://github.com/nektos/act.

I will keep you informed.

**Comment by vzamanillo** [comment]
Lot of work but...

![lint](https://user-images.githubusercontent.com/10209695/88290605-54357780-ccf7-11ea-8a48-707ab0acc32a.png)

#278

:)

**Comment by bauthard** [comment]
Done with https://github.com/projectdiscovery/subfinder/pull/278
