### ISSUE TITLE
[Feature] Adding urlscan source

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/subfinder#282]
**Is your feature request related to a problem? Please describe.**
We were using an unofficial version of urlscan API resulting in multiple issues, as such we dropped the old support here https://github.com/projectdiscovery/subfinder/commit/ef224dc1b1e5867d5b50c4b4757700f2dc3dd381 and will be adding again using the official version of API, as recently URLscan announced and came up with API support. 

**Describe the solution you'd like**
API Documentation:- https://urlscan.io/about-api/

**Comment by ZeroDot1** [comment]
That sounds good.

**Comment by bauthard** [comment]
Closing this one, as we will focusing on utilizing existing sources in the best possible way, new sources will be added only when we are getting new results using new sources compared to existing sources.
