### ISSUE TITLE
Not able to start!

### ISSUE THREAD

**Issue by ivasugarg** [projectdiscovery/subfinder#288]
$go run main.go   

'#  github.com/projectdiscovery/subfinder/pkg/subscraping
../../pkg/subscraping/agent.go:63:14: undefined: http.NewRequestWithContext
note: module requires Go 1.14

**Comment by Ice3man543** [comment]
@ivasugarg As mentioned by the message, this tool requires atleast go version 1.14 to work. So please update your go environment and try again. Closing this issue. In future, we'll update the Documentation to specify required version.
