### ISSUE TITLE
[Issue] mkdir permission denied

### ISSUE THREAD

**Issue by gbiagomba** [projectdiscovery/subfinder#293]
**Describe the bug**
[FTL] Could not get user home: mkdir /home/ubuntu/.config/subfinder: permission denied

**Subfinder version**
Include the version of subfinder you are using, `subfinder -version`
I am guessing its the latest version as of the day of posting, i used "go get -u -v github.com/projectdiscovery/subfinder/cmd/subfinder"

**Complete command you used to reproduce this**
subfinder -h

**Screenshots**
Add screenshots of the error for a better context.
See above

**Comment by gbiagomba** [comment]
in case this helps 
```
Linux kali 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 GNU/Linux
```

**Comment by bauthard** [comment]
Are you able to create this dir manually? try to execute this `mkdir /home/ubuntu/.config/subfinder`

**Comment by gbiagomba** [comment]
yea that was the first thing i tried @bauthard and it didnt fix it. Mind you am only getting that issue on my ubuntu server not on my mac. I even tried seeing it there was data in the config file and when i tried catting it on mac it was empty. So am not sure why its giving me that issue.

**Comment by bauthard** [comment]
as the error indicates, it's permission related issue with the user you are running on the system.

**Comment by gbiagomba** [comment]
i tried both plain and sudo, i even tried using sudo -EH and none of it worked @bauthard only thing i didnt try yet was uninstalling and reinstalling lol

**Comment by bauthard** [comment]
You can simply download the binary form here https://github.com/projectdiscovery/subfinder/releases if it works @gbiagomba

**Comment by gbiagomba** [comment]
@bauthard i will try that next but i tried changing the folder permissions and it still wont load
```
ubuntu@kali:~$ sudo ls -al /home/ubuntu/.config/subfinder
total 8
drwxr-xr-x 2 root root 4096 Aug 13 17:26 .
drwx------ 4 root root 4096 Aug 13 17:26 ..
ubuntu@kali:~$ sudo -EH subfinder --help
sudo: subfinder: command not found
ubuntu@kali:~$ sudo -H subfinder --help
sudo: subfinder: command not found
ubuntu@kali:~$ sudo chown ubuntu /home/ubuntu/.config/subfinder
ubuntu@kali:~$ sudo ls -al /home/ubuntu/.config/subfinder
total 8
drwxr-xr-x 2 ubuntu root 4096 Aug 13 17:26 .
drwx------ 4 root   root 4096 Aug 13 17:26 ..
ubuntu@kali:~$ subfinder --help
[FTL] Could not get user home: mkdir /home/ubuntu/.config/subfinder: permission denied
```

**Comment by gbiagomba** [comment]
@bauthard whats the ddiference between these two(2)?
```
subfinder_2.4.1_linux_amd64.tar.gz
4.14 MB
subfinder_2.4.1_linux_arm64.tar.gz
3.79 MB
```

**Comment by vzamanillo** [comment]
```
drwxr-xr-x 2 ubuntu root 4096 Aug 13 17:26 .
drwx------ 4 root   root 4096 Aug 13 17:26 ..
```

You need permissions on the parent dir, your `.config` dir can not be traversed because it has not the execution permission.

`$ chmod a+x ~/.config`

**Comment by gbiagomba** [comment]
but the user (ubuntu nor root) has exec permissions. But downloading the standalone fixed it, and i will give this a try nonetheless and let u know. @vzamanillo

**Comment by vzamanillo** [comment]
Could we close this?

**Comment by gbiagomba** [comment]
apoloties @vzamanillo im just seeing htis but yes i know it is already closed but yes if i run into any other issues i will either reopen this one or open a new one and reference this (assuming the issue is the same)
