### ISSUE TITLE
resolver syntax

### ISSUE THREAD

**Issue by Sy3Omda** [projectdiscovery/subfinder#294]
Hi,

i was wondering what is the syntax for resolvers.txt file?
my file is as following 
```
8.8.8.8
8.8.4.4
1.1.1.1
```
and so on , dose this need to modify !

**Comment by bauthard** [comment]
Yes, that's the correct format, also for resolving we do suggest to use [shuffledns](https://github.com/projectdiscovery/shuffledns) and you can pipe it with subfinder + wildcard filtering as well. 

```
subfinder -d uber.com | shuffledns -d uber.com -r resolvers.txt
```
