### ISSUE TITLE
brute force list as a feature 

### ISSUE THREAD

**Issue by Sy3Omda** [projectdiscovery/subfinder#299]
Hi,

i noticed that the readme dosn`t have flag for brute force feature, so
is it possible to enable it soon ?

thx

**Comment by bauthard** [comment]
Hey @Sy3Omda, 

We are focusing at one feature at a time, consider **subfinder** as **passive subdomain enumeration tool**, for bruteforce or resolving, we have [shuffledns](https://github.com/projectdiscovery/shuffledns) and [dnsprobe](https://github.com/projectdiscovery/dnsprobe).
