### ISSUE TITLE
[Feature] Add support for WhoisXML

### ISSUE THREAD

**Issue by geeknik** [projectdiscovery/subfinder#300]
**Is your feature request related to a problem? Please describe.**
Hi and thank you for this great piece of software. Please add support for https://www.whoisxmlapi.com/. Thank you.

**Describe the solution you'd like**
API documentation: https://subdomains.whoisxmlapi.com/api/documentation/making-requests

**Comment by bauthard** [comment]
This request is being tracked here https://github.com/projectdiscovery/subfinder/issues/301
