### ISSUE TITLE
[Feature] Request for Sources Addition

### ISSUE THREAD

**Issue by Avileox** [projectdiscovery/subfinder#301]
#### Sources with API Support:

- [x] alienvault [Api Support]
- [x] zoomeye [Api Support]
- [x] ipv4info [Api Support]
- [x] fofa.so [Api Support]
- [x] intelx.io [Api Support]
- [x] ThreatBook [Api Support]
- [ ] Cloudflare [Api Support]
- [ ] ZETAlytics [Api Support]
- [ ] WhoisXML [Api Support]
- [ ] NetworksDB [Api Support]
- [ ] CIRCL [Api Support]
- [ ] viewdns [Api Support]
- [ ] c99.nl [Api Support]
- [ ] Chinaz [Api Support]

 

#### Sources without API Support:

- [x] ximc
- [x] anubisdb
- [x] robtex
- [x] cebaidu
- [x] riddler.io 
- [ ] ancestry
- [ ] wzpc
- [ ] qianxun
- [ ] ptrarchive
- [ ] ip138
- [ ] mnemonic.no
- [ ] threatminer
- [ ] sonarsearchit.io

#### Some Extra Source for -all enumeration option as they can be time taking:

- [ ] facebook
- [ ] bing [Api Support]
- [ ] googlect [Api Support]
- [ ] baidu
- [ ] pastebin
- [ ] locarchive
- [ ] ukgovarchive
- [ ] yahoo
- [ ] archive.vn

**Comment by bauthard** [comment]
`intelx` is already part of subfinder.

**Comment by vzamanillo** [comment]
ximc is implemented,  WhoisXML not yet.

**Comment by bauthard** [comment]
Thank you @Avileox for the issue and @vzamanillo for adding multiple sources, closing this issue now, as from now on we will be focusing on utilizing existing sources in the best possible way, new sources will be added only when we are getting new results using new sources compared to existing sources.
