### ISSUE TITLE
i have problem 

### ISSUE THREAD

**Issue by shadihh9** [projectdiscovery/subfinder#305]
**Describe the bug**
when i run  subfinder -d riotgames.com -oI IP.txt not run 
**Subfinder version**
2.3.4

**Complete command you used to reproduce this**

**Screenshots**
Add screenshots of the error for a better context.
![wwwwwww](https://user-images.githubusercontent.com/22076930/92323225-a6302380-f03f-11ea-9712-70de893b4534.png)

**Comment by vzamanillo** [comment]
You have to use the `-nW` flag to remove wildcard domains.

**Comment by bauthard** [comment]
As suggested, you need to use `nW`, the same indicated in the error as well.
