### ISSUE TITLE
-all not working

### ISSUE THREAD

**Issue by 80c6qha** [projectdiscovery/subfinder#306]
there is a bug when i use -all arg...

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x7ac576]

goroutine 63 [running]:
github.com/projectdiscovery/subfinder/pkg/subscraping/sources/github.proccesItems(0xa15d00, 0xc00008e060, 0xc000330000, 0x64, 0x80, 0xc0002480a0, 0x95dbdb, 0x6, 0xc00008a000, 0xc000200780, ...)
        /home/runner/work/subfinder/subfinder/pkg/subscraping/sources/github/github.go:145 +0x226
github.com/projectdiscovery/subfinder/pkg/subscraping/sources/github.(*Source).enumerate(0xd96fd8, 0xa15d00, 0xc00008e060, 0xc00032a92c, 0x5b, 0xc0002480a0, 0xc0002101e0, 0xc00008a000, 0xc000200780)
        /home/runner/work/subfinder/subfinder/pkg/subscraping/sources/github/github.go:112 +0x530
github.com/projectdiscovery/subfinder/pkg/subscraping/sources/github.(*Source).enumerate(0xd96fd8, 0xa15d00, 0xc00008e060, 0xc00032a76c, 0x5b, 0xc0002480a0, 0xc0002101e0, 0xc00008a000, 0xc000200780)
        /home/runner/work/subfinder/subfinder/pkg/subscraping/sources/github/github.go:128 +0x6d3
github.com/projectdiscovery/subfinder/pkg/subscraping/sources/github.(*Source).enumerate(0xd96fd8, 0xa15d00, 0xc00008e060, 0xc00032a22c, 0x5b, 0xc0002480a0, 0xc0002101e0, 0xc00008a000, 0xc000200780)
        /home/runner/work/subfinder/subfinder/pkg/subscraping/sources/github/github.go:128 +0x6d3
github.com/projectdiscovery/subfinder/pkg/subscraping/sources/github.(*Source).enumerate(0xd96fd8, 0xa15d00, 0xc00008e060, 0xc00032a5ac, 0x5b, 0xc0002480a0, 0xc0002101e0, 0xc00008a000, 0xc000200780)
        /home/runner/work/subfinder/subfinder/pkg/subscraping/sources/github/github.go:128 +0x6d3
github.com/projectdiscovery/subfinder/pkg/subscraping/sources/github.(*Source).enumerate(0xd96fd8, 0xa15d00, 0xc00008e060, 0xc00032a3ec, 0x5b, 0xc0002480a0, 0xc0002101e0, 0xc00008a000, 0xc000200780)
        /home/runner/work/subfinder/subfinder/pkg/subscraping/sources/github/github.go:128 +0x6d3
github.com/projectdiscovery/subfinder/pkg/subscraping/sources/github.(*Source).enumerate(0xd96fd8, 0xa15d00, 0xc00008e060, 0xc00016c06c, 0x5b, 0xc0002480a0, 0xc0002101e0, 0xc00008a000, 0xc000200780)
        /home/runner/work/subfinder/subfinder/pkg/subscraping/sources/github/github.go:128 +0x6d3
github.com/projectdiscovery/subfinder/pkg/subscraping/sources/github.(*Source).enumerate(0xd96fd8, 0xa15d00, 0xc00008e060, 0xc00032a06c, 0x5b, 0xc0002480a0, 0xc0002101e0, 0xc00008a000, 0xc000200780)
        /home/runner/work/subfinder/subfinder/pkg/subscraping/sources/github/github.go:128 +0x6d3
github.com/projectdiscovery/subfinder/pkg/subscraping/sources/github.(*Source).enumerate(0xd96fd8, 0xa15d00, 0xc00008e060, 0xc0001281c1, 0x5b, 0xc0002480a0, 0xc0002101e0, 0xc00008a000, 0xc000200780)
        /home/runner/work/subfinder/subfinder/pkg/subscraping/sources/github/github.go:128 +0x6d3
github.com/projectdiscovery/subfinder/pkg/subscraping/sources/github.(*Source).enumerate(0xd96fd8, 0xa15d00, 0xc00008e060, 0xc0002007e0, 0x54, 0xc0002480a0, 0xc0002101e0, 0xc00008a000, 0xc000200780)
        /home/runner/work/subfinder/subfinder/pkg/subscraping/sources/github/github.go:128 +0x6d3
github.com/projectdiscovery/subfinder/pkg/subscraping/sources/github.(*Source).Run.func1(0xc000200780, 0xc00008a000, 0xc000018100, 0xb, 0xd96fd8, 0xa15d00, 0xc00008e060)
        /home/runner/work/subfinder/subfinder/pkg/subscraping/sources/github/github.go:55 +0x1d1
created by github.com/projectdiscovery/subfinder/pkg/subscraping/sources/github.(*Source).Run
        /home/runner/work/subfinder/subfinder/pkg/subscraping/sources/github/github.go:45 +0xa5

**Screenshots**
![image](https://user-images.githubusercontent.com/70751674/92372815-0f8f5f80-f130-11ea-9e85-8ea8e5e8ee2a.png)

**Comment by cybertix** [comment]
Yes I am having the exact same issue. And it happens only when using -all flag.
And please do note that for me it does not happens every time. Sometimes it just runs perfectly

**Comment by vzamanillo** [comment]
This will be reviewed ASAP. Thanks for reporting.

**Comment by cybertix** [comment]
@vzamanillo  I also want to add one more thing. I have noticed a strange behavior. Whenever i run subfinder against a **.nl** root domain with -all flag, it always gives the upper mentioned error.
But If I run the same against a **.com** domain, most of the times it runs perfectly but it does break a few times though.

**Comment by vzamanillo** [comment]
It is an dumb bug... xD

**Comment by bauthard** [comment]
@80c6qha @cybertix this should be fixed in the latest release, thank you @vzamanillo for jumping on this.

**Comment by cybertix** [comment]
> @80c6qha @cybertix this should be fixed in the latest release, thank you @vzamanillo for jumping on this.

Yes just tested it. It is fixed. Thanks
