### ISSUE TITLE
[Issue] No IP info on -oJ and -nW switches

### ISSUE THREAD

**Issue by lwierzbicki** [projectdiscovery/subfinder#307]
**Describe the bug**
No IP info presented on output from tool runs with `-oJ` and `-nW` switches. This behavior encountered on newly installed subfinder version  2.4.3 with some API keys configured. I only get `host` and `source`, without `ip` in JSON line. All info (means `host`, `ip`,`source` is presented when `-oI` switch is used and output like CSV (with comma delimeter)
On subfinder version 2.3.8 I got `host` and `ip` when use `-oJ` and `-nW` switches
Documentation example:
```
> subfinder -d hackerone.com -o output.json -oJ -nW
> cat output.json

{"host":"www.hackerone.com","ip":"104.16.99.52"}
{"host":"mta-sts.hackerone.com","ip":"185.199.108.153"}
{"host":"hackerone.com","ip":"104.16.100.52"}
{"host":"mta-sts.managed.hackerone.com","ip":"185.199.110.153"}
```

**Subfinder version**
Include the version of subfinder you are using, `subfinder -version`
2.4.3

**Complete command you used to reproduce this**
Command `subfinder -d "engadget.com"  -o test.json -oJ -nW -all -v`. 

**Screenshots**
![subfinder](https://user-images.githubusercontent.com/1812393/92413108-db776700-f14e-11ea-81d2-7b6fa49472d9.PNG)

**Comment by bauthard** [comment]
Hi @lwierzbicki, 

Yes, we made some changes in the recent version, you can get the expected results with the followings:- 

```
 subfinder -d hackerone.com -o output.json -oJ -oI -nW
```
