### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by nine9-nine9** [projectdiscovery/subfinder#328]
**Describe the bug**
When running subfinder with the -all flag I get a panic runtime error!! The error seems to be the sitedossier source. After excluding it fro sources it runs quite well!

**Subfinder version**
Include the version of subfinder you are using, `subfinder -version 2.4.5`

**Complete command you used to reproduce this**
subfinder -d uber.com -v -all

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/70813379/93866050-dc240780-fccf-11ea-93af-2416ab6b90fe.png)

**Comment by vzamanillo** [comment]
Hey! 2.4.5 is not released yet, are you running `subfinder` from the master branch?

**Comment by nine9-nine9** [comment]
Yes...

Shouldnt I complie from master

**Comment by vzamanillo** [comment]
I am testing with the latest `master` branch and I can't reproduce this, could you please try again?

The `master` branch is subject to possible errors between releases, anyway thank you for reporting this.

**Comment by nine9-nine9** [comment]
So on 2.4.5 the sitedossier source gets the runtime error, but version 2.4.4 runs just fine.
I have attached screenshots and i shall revert back to v2.4.4

![2 4 4](https://user-images.githubusercontent.com/70813379/93870984-a5052480-fcd6-11ea-8191-713fccfbbee5.png)

![2 4 5](https://user-images.githubusercontent.com/70813379/93871002-aafb0580-fcd6-11ea-959e-71f935c259cb.png)

**Comment by vzamanillo** [comment]
With the latest master branch `sitedossier` has no problem, anyway, the normal thing is to always use the latest release, use the master branch as I said before, it is subject to possible errors.
