### ISSUE TITLE
Free 100 bug bounty video lessons 

### ISSUE THREAD

**Issue by udaydatrak** [projectdiscovery/subfinder#338]
Hi Guys,

I made a video on how to learn 100 unique security issues learning in just 20 hours without any basics.

I would like you to add these in your features list. People from across the globe already started giving hundreds of positive comments.

Search in YouTube for "100 bug bounty lessons uday datrak" To learn including web application development and setup too.

https://www.youtube.com/playlist?list=PL_bkTzUc1BufnQyGt6-9hSly2PqsDmd09

**Comment by bauthard** [comment]
Hi @udaydatrak, 

Thank you, feel free to use the tool or name as it fits for you, thank you for making and sharing content for the community.
