### ISSUE TITLE
[Issue] Panic when using invalid IntelX host

### ISSUE THREAD

**Issue by 003random** [projectdiscovery/subfinder#339]
**Describe the bug**
It seems like when using public.intelx.io as host in the IntelX key, it will trow a panic. I accidentally set this host in instead of 2.intelx.io (the public one was mentioned somewhere in the subfinder docs and the 2.intelx one was on the intelx dashboard).

The panic seems to be thrown on the defer close(results) which will be called at line 77 just before the return. The error in the if statement is an EOF error because public.intelx.io will return an empty response.

The panic:

```sh
root:subfinder-test/ $ go run main.go
could not run source shodan: readObjectStart: expect { or n, but found <, error found in #1 byte of ...|<!DOCTYPE H|..., bigger context ...|<!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta |...
panic: close of closed channel

goroutine 51 [running]:
github.com/projectdiscovery/subfinder/pkg/subscraping/sources/intelx.(*Source).Run.func1(0xc00008e0c0, 0xc000115200, 0x974b98, 0xb, 0xdb84d0, 0xa2b320, 0xc000068b40)
        /root/work/src/github.com/projectdiscovery/subfinder/pkg/subscraping/sources/intelx/intelx.go:77 +0xaa2
created by github.com/projectdiscovery/subfinder/pkg/subscraping/sources/intelx.(*Source).Run
        /root/work/src/github.com/projectdiscovery/subfinder/pkg/subscraping/sources/intelx/intelx.go:45 +0x9e
exit status 2
```

**Subfinder version**
2.4.5

**Complete command you used to reproduce this**

```sh
package main

import (
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/projectdiscovery/subfinder/pkg/passive"
	"github.com/projectdiscovery/subfinder/pkg/runner"
	"github.com/projectdiscovery/subfinder/pkg/subscraping"
)

func main() {
	domain := "redbull.com"
	configDir, err := runner.GetConfigDirectory()
	if err != nil {

	}
	cf, err := runner.UnmarshalRead(configDir + "/config.yaml")
	if err != nil {

	}
	session, err := subscraping.NewSession(domain, cf.GetKeys(), 10)
	if err != nil {
		log.Fatal(err)
	}

	// Subfinders agent. Required
	agent := passive.New(passive.DefaultSources, []string{})

	results := agent.EnumerateSubdomains(domain, session.Keys, 30, 90*time.Second)
	for r := range results {
		switch r.Type {
		case subscraping.Error:
			fmt.Printf("could not run source %s: %s\n", r.Source, r.Error)
		case subscraping.Subdomain:
			if !strings.HasSuffix(r.Value, "."+domain) {
				continue
			}
			// subdomain := strings.ReplaceAll(strings.ToLower(r.Value), "*.", "")
			// fmt.Println(subdomain)
		}
	}
}
```

**Screenshots**
![code](https://user-images.githubusercontent.com/22357749/95470556-3932e500-0981-11eb-88ac-dc31df656b7a.png)

**Comment by 003random** [comment]
Nice github -.- very good formatting

**Comment by 003random** [comment]
https://gist.github.com/003random/4bd601003dae9941857ceecd2e91d7cf i uploaded the code to a gist

**Comment by 003random** [comment]
use that code + set the intelx key to  public.intelx.io:your-valid-key-here

**Comment by 003random** [comment]
Its stupid that i cant remember where i got it from to set public.intelx.io as host. I think i saw "<public.intelx.io:yourkey>" somewhere but cant find it. At least im certain i didnt make it up because i didnt even know public.intelx.io existed as subdomain ahah. never worked with intelx

**Comment by bauthard** [comment]
@003random thank you for reporting this, this is a known bug when you submit an unexpected hostname in the config file.

**Comment by Kleissner** [comment]
The formerly public API instance `public.intelx.io` is discontinued (see also this [blog post](https://blog.intelx.io/2020/08/27/newsletter-2020-08-27/)).
Users must use `2.intelx.io` (you can hardcode that host) and the API key provided at https://intelx.io/account?tab=developer (the API key must be provided by the user via a config file).

**Comment by Mzack9999** [comment]
Closing as the correct host should be specified in the config file
