### ISSUE TITLE
Error in installing

### ISSUE THREAD

**Issue by learn-alam** [projectdiscovery/subfinder#340]
**undefined: http.NewRequestWithContext**
after installing when i run go build in subfinder/v2/cmd/subfinder directory it show above error.
how to fix it.

![Screenshot from 2020-10-14 22-35-51](https://user-images.githubusercontent.com/66875769/96022244-3303a380-0e6e-11eb-9481-9001ed39d767.png)

**Comment by bauthard** [comment]
Hey @learn-alam, 

You are running an older version of Go, to install subfinder make sure you are running the latest or 1.14+ go version or simply download ready to use binary for your system from here https://github.com/projectdiscovery/subfinder/releases

**Comment by learn-alam** [comment]
Hey @bauthard 
Thanks for your help. 
Subfinder installed successfully .
