### ISSUE TITLE
[Feature] Filter only first level subdomain

### ISSUE THREAD

**Issue by dawadam** [projectdiscovery/subfinder#344]
Some services have second level subdomains (aaa.bbb.website.com), it would be practical to only be able to filter the top level subdomains (bbb.website.com).
Or define the maximum subdomain depth.

**Comment by bauthard** [comment]
Hi @dawadam, 

Thank you for creating this issue, but this looks like out of scope for the Subfinder project, what you requesting here can be achieved by simple text processing that includes only 1st order of subdomains, as this is something will not be implemented in the project, as such closing this issue.
