### ISSUE TITLE
[Issue] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by maruthupandiyanv** [projectdiscovery/subfinder#357]
**Describe the bug**
Using all sources subfinder -d uber.com -all  an error occur
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7ceb72]

goroutine 112 [running]:
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/sitedossier.(*agent).enumerate(0xc00014f6d0, 0xa15760, 0xc0000b08a0, 0xc000098480, 0x30)
        /root/go/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.4.5/pkg/subscraping/sources/sitedossier/sitedossier.go:40 +0x192
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/sitedossier.(*Source).Run.func1(0xc00014f6d0, 0xa15760, 0xc0000b08a0, 0x7ffc2132ad35, 0x8)
        /root/go/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.4.5/pkg/subscraping/sources/sitedossier/sitedossier.go:73 +0xc6
created by github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/sitedossier.(*Source).Run
        /root/go/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.4.5/pkg/subscraping/sources/sitedossier/sitedossier.go:72 +0xc5
```
**Subfinder version**
v2.4.5

**Comment by bauthard** [comment]
Hi @maruthupandiyanv, 

This is already fixed in the `dev` branch https://github.com/projectdiscovery/subfinder/commit/b3c582d3ad0e5d61e7a8b611b00e8832ee6d2fc5

**Comment by maruthupandiyanv** [comment]
hi how to update to the fixed version

**Comment by bauthard** [comment]
Hey, 

You can clone the project and do `git checkout dev` and move to `cd v2/cmd/subfinder` and do `go build`. 

Please keep in mind `dev` branch is supposed to use for development so there will be ongoing changes that might break things for you, so either you can wait till we create a new stable release and use it by excluding this source `-exclude-sources sitedossier`

**Comment by maruthupandiyanv** [comment]
@bauthard thanks team

**Comment by storenth** [comment]
Do you plan to merge fix-changes in `master`?

**Comment by bauthard** [comment]
Yes, we have more chances to update along with this and we will push the code to master and create a new release after that.
