### ISSUE TITLE
[Issue] New lines in the output with passivetotal source  

### ISSUE THREAD

**Issue by ZeroDot1** [projectdiscovery/subfinder#359]
**Describe the bug**
When checking for subdomains, there are unfortunately repeatedly incorrect entries see example.

**Example**
```bash
194.67.71.144\032italo.alisepool.xyz
45.66.9.81\032blackrose.alisepool.xyz
45.66.9.81\032seva.alisepool.xyz
194.67.71.70\032blackrose.alisepool.xyz

```

**Subfinder version**
v2.4.5

**Complete command you used to reproduce this**
`subfinder -sources passivetotal -d alisepool.xyz`

**Comment by ZeroDot1** [comment]
OK, after a few URLs I can say that the problem occurs very often.
![Bildschirmfoto vom 2021-01-04 05-15-20](https://user-images.githubusercontent.com/28985171/103500608-dbad1800-4e4b-11eb-82ed-623eb33ba206.png)

**Comment by bauthard** [comment]
Hi @ZeroDot1, 

Looks like something got changed with `passivetotal` source, for the time being, you can run the scans by excluding this particular source `-exclude-sources passivetotal`

**Comment by ZeroDot1** [comment]
Yes, the solution works, thanks for the quick reply.

**Comment by ehsandeep** [comment]
This is fixed with https://github.com/projectdiscovery/subfinder/pull/375
