### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by maK-** [projectdiscovery/subfinder#360]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when you change the build instructions and paths, as it's the only project I have to keep updating regularly to install and build. It's a minor grievance but worth mentioning.

**Describe the solution you'd like**
It's such a great tool and I'm absolutely a massive fan, it would be even better though if you kept the install paths and install instructions consistent across builds. 

Keep up the great work otherwise folks <3

**Comment by bauthard** [comment]
Thank you for sharing the feedback @maK-, definitely, we will ensure to keep the project as stable as we can.
