### ISSUE TITLE
[Feature] rate limit support for http requests

### ISSUE THREAD

**Issue by ZeroDot1** [projectdiscovery/subfinder#362]
Add a function to make a random delay between the requests.
The user should have the possibility to set a time delay, e.g. a random delay from 1 to 10 seconds.
This function helps not to be blocked directly by the different services when you make a lot of requests.

**Comment by ehsandeep** [comment]
For this, a new flag, say `delay`, can be added to ensure that the user-defined delay between each HTTP request sent from SubFinder is respected.

```
-delay         Seconds to wait between requests (default 0)
```

Example use:-

```
subfinder -d example.com -delay 2
```
