### ISSUE TITLE
[Feature] Wildcards check support multi-level subdomain

### ISSUE THREAD

**Issue by lostsnow** [projectdiscovery/subfinder#365]
**Is your feature request related to a problem? Please describe.**

Currently wildcards check only support *.domain.com

**Describe the solution you'd like**

Hope to support multi-level subdomains such as *.foo.domain.com, *.bar.foo.domain.com, etc.

**Comment by bauthard** [comment]
@lostsnow do you have some examples to share that we can use for evaluation?

**Comment by lostsnow** [comment]
> 
> 
> @lostsnow do you have some examples to share that we can use for evaluation?

*.114.qq.com

```
;; ANSWER SECTION:
4006505080.114.qq.com.  569     IN      A       125.39.133.28
```

```
;; ANSWER SECTION:
e9b0ba0e20c7d682a.114.qq.com. 600 IN    A       125.39.133.28
```

**Comment by ehsandeep** [comment]
SubFinder uses dnsx for active resolutions, it will be done as part of dnsx and tracking here https://github.com/projectdiscovery/dnsx/issues/34
