### ISSUE TITLE
Writing to a non-existent directory

### ISSUE THREAD

**Issue by codingo** [projectdiscovery/subfinder#38]
If output is specified to a non-existent directory the output write will fail with:

> 
error : open /root/Documents/Bounties/domain.com/subdomains.txt: no such file or directory#   

Output should check for the existence of a directory before running a scan, or alternatively write the directory to disk if it doesn't yet exist.

**Comment by Ice3man543** [comment]
I was thinking of the exact same thing yesterday while running my scans. Will change it now :+1:
