### ISSUE TITLE
[Issue] <br> tag in output with anubis source

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/subfinder#398]
Workaround:-

a) excluding source form scan:- 
```
subfinder -d example.com exclude-sources anubis
```
b) removing from `anubis` from config file at `~/.config/subfinder/config.yaml`

**Comment by vzamanillo** [comment]
I think this is not a bug, the br tag comes from the source itself, it is not a parsing problem because the provider responses with a `json`

![2021-02-27_11-44](https://user-images.githubusercontent.com/10209695/109385066-66147400-78f1-11eb-9acd-2ea33561ef2f.png)

**Comment by ehsandeep** [comment]
Closing as this is not an issue in parsing and results will be filtered with DNS resolution.
