### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bugpie54** [projectdiscovery/subfinder#402]
**Describe the bug**
The error occured when using the -nW flag

**Subfinder version**
Version: 2.4.6

**Complete command you used to reproduce this**
subfinder -d hackerone.com -nW

**Error**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x88a5aa]

goroutine 1 [running]:
github.com/projectdiscovery/dnsx/libs/dnsx.(*DNSX).Lookup(0xc00000fba0, 0xc00002a330, 0x22, 0x9c1cbb, 0x1, 0x7fff4e36040f, 0xd, 0xc00002a330)
        /home/user/go/pkg/mod/github.com/projectdiscovery/dnsx@v1.0.1/libs/dnsx/dnsx.go:57 +0x10a
github.com/projectdiscovery/subfinder/v2/pkg/resolve.(*ResolutionPool).InitWildcards(0xc00015bb90, 0x7fff4e36040f, 0xd, 0xc00015bb90, 0x24)
        /home/user/go/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.4.6/pkg/resolve/resolve.go:78 +0x1ca
github.com/projectdiscovery/subfinder/v2/pkg/runner.(*Runner).EnumerateSingleDomain(0xc00000fb60, 0xa68060, 0xc0000240e8, 0x7fff4e36040f, 0xd, 0x0, 0x0, 0xc000157e00, 0x0, 0x0)
        /home/user/go/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.4.6/pkg/runner/enumerate.go:31 +0x1705
github.com/projectdiscovery/subfinder/v2/pkg/runner.(*Runner).RunEnumeration(0xc00000fb60, 0xa68060, 0xc0000240e8, 0x0, 0xc00006a6c0)
        /home/user/go/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.4.6/pkg/runner/runner.go:44 +0x1e9
main.main()
        /home/user/go/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.4.6/cmd/subfinder/main.go:21 +0x72

**go version**
go version go1.16 linux/amd64

**Comment by ValluvarSploit** [comment]
I faced this issue in v2.4.3. It's resolved in new release.

**Comment by ehsandeep** [comment]
@bugpie54 this was an issue with the older version and fixed in the latest version, can you make sure to run this with latest binary?

```
./subfinder -d hackerone.com -nW

        _     __ _         _
____  _| |__ / _(_)_ _  __| |___ _ _
(_-< || | '_ \  _| | ' \/ _  / -_) '_|
/__/\_,_|_.__/_| |_|_||_\__,_\___|_| v2.4.6

		projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
By using subfinder, you also agree to the terms of the APIs used.

[INF] Enumerating subdomains for hackerone.com
mta-sts.managed.hackerone.com
api.hackerone.com
hackerone.com
b.ns.hackerone.com
resources.hackerone.com
mta-sts.hackerone.com
docs.hackerone.com
www.hackerone.com
mta-sts.forwarding.hackerone.com
a.ns.hackerone.com
support.hackerone.com
[INF] Found 11 subdomains for hackerone.com in 2 seconds 634 milliseconds
```

**Comment by bugpie54** [comment]
I did run it with the latest binary which i downloaded from the releases page! am i missing something here?!
