### ISSUE TITLE
[Feature] add source website fofa.so

### ISSUE THREAD

**Issue by c2xusnpq6** [projectdiscovery/subfinder#408]
https://fofa.so just like censys or zoomeye

**Comment by c2xusnpq6** [comment]
ping?

**Comment by ehsandeep** [comment]
Hey @c2xusnpq6, 

Thanks for the ping, unfortunately, we don't have an API key for this website and unable to complete the complex signup process, and without the key, we can not start to work on this source.

**Comment by c2xusnpq6** [comment]
https://github.com/fofapro

https://github.com/fofapro/fofa-py
https://github.com/fofapro/fofa-java
https://github.com/fofapro/fofa-go
https://github.com/fofapro/fofa-c

**Comment by Becivells** [comment]
@c2xusnpq6 ping?
