### ISSUE TITLE
[Issue] invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by GDATTACKER-RESEARCHER** [projectdiscovery/subfinder#412]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x89326a]

goroutine 1 [running]:
github.com/projectdiscovery/dnsx/libs/dnsx.(*DNSX).Lookup(0xc00000fbc0, 0xc000029d40, 0x20, 0x9cd3db, 0x1, 0x7fff54ec06a7, 0xb, 0xc000029d40)
	/root/go/pkg/mod/github.com/projectdiscovery/dnsx@v1.0.2/libs/dnsx/dnsx.go:56 +0x10a
github.com/projectdiscovery/subfinder/v2/pkg/resolve.(*ResolutionPool).InitWildcards(0xc000155aa0, 0x7fff54ec06a7, 0xb, 0xc000155aa0, 0x24)
	/root/go/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.4.7/pkg/resolve/resolve.go:78 +0x1e5
github.com/projectdiscovery/subfinder/v2/pkg/runner.(*Runner).EnumerateSingleDomain(0xc00000fb60, 0xa74040, 0xc0000240a8, 0x7fff54ec06a7, 0xb, 0x7fff54ec06bd, 0x4a, 0xc000151e00, 0x0, 0x0)
	/root/go/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.4.7/pkg/runner/enumerate.go:31 +0x1725
github.com/projectdiscovery/subfinder/v2/pkg/runner.(*Runner).RunEnumeration(0xc00000fb60, 0xa74040, 0xc0000240a8, 0x0, 0xc000068660)
	/root/go/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.4.7/pkg/runner/runner.go:44 +0x1e9
main.main()
	/root/go/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.4.7/cmd/subfinder/main.go:21 +0x72

**Comment by ehsandeep** [comment]
@GDATTACKER-RESEARCHER Can you share the command you used to reproduce this? with output of `subfinder -version`

**Comment by GDATTACKER-RESEARCHER** [comment]
Cat 1|subfinder -all|tee 11  sorry wrote  wrong first

**Comment by ehsandeep** [comment]
@GDATTACKER-RESEARCHER `-all` flag only collects the passive data and does not make use of dnsx, unless you use `-nW` flag, can you check and confirm this again?

**Comment by GDATTACKER-RESEARCHER** [comment]
it comes sometimes not always so maybe needs a long time analysis.

**Comment by ehsandeep** [comment]
It was an issue with dnsx, and fixed in this PR https://github.com/projectdiscovery/subfinder/pull/417

**Comment by ehsandeep** [comment]
Fixed added into master and latest release, [v2.4.8](https://github.com/projectdiscovery/subfinder/releases/tag/v2.4.8)
