### ISSUE TITLE
Add subdomains from waybackurls [Feature] 

### ISSUE THREAD

**Issue by wanted1205** [projectdiscovery/subfinder#427]
**Is your feature request related to a problem? Please describe.**
Aquatone-discover was having a functionality to gather subdomains from wayback  

**Describe the solution you'd like**
This tools gathers urls from wayback https://github.com/tomnomnom/waybackurls/blob/master/main.go you can use it to gather urls from wayback and can collect subdomains

**Comment by ehsandeep** [comment]
@wanted1205 it's already supported, `-sources waybackarchive` as in this source is quite slow, it's excluded from default subfinder scan, in case you want to use it, either you can use `-all` flag that will include all sources or to run this specific source you can use `-sources waybackarchive`
