### ISSUE TITLE
[Feature] Wordlist search

### ISSUE THREAD

**Issue by iburkhardt** [projectdiscovery/subfinder#435]
Currently I use amass in my searches for subdomains, they have the option to add wordlist, could you implement this feature?

**Comment by ehsandeep** [comment]
Hi @iburkhardt, 

SubFinder is a passive subdomain discovery framework, what you suggesting here involves active/DNS Bruteforce that can be done with shuffledns / amass / puredns or any project involving active discovery.

Closing this issue as it is out of scope for this project.
