### ISSUE TITLE
[Issue] Installation fails: go get deprecated for executables

### ISSUE THREAD

**Issue by Perdyx** [projectdiscovery/subfinder#462]
**Description**

Running the command included in the installation instructions fails due to golang deprecating `go get` for executables.

```
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

**Subfinder version**

v2.4.8

**Command used**

`GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder`

**Comment by ehsandeep** [comment]
@Perdyx you can use `go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@dev` to install for now, I've updated the readme here - https://github.com/projectdiscovery/subfinder/commit/4190e0f0e9c795bb7b55dedc1bc39484716c9426

**Comment by Perdyx** [comment]
Thank you!
