### ISSUE TITLE
Subfinder stopped working on my machine 

### ISSUE THREAD

**Issue by harikkrish** [projectdiscovery/subfinder#470]
Hi,
Subfinder suddenly stopped working on my machine. Whenever I tried to run, I'm getting the following error. 

### Subfinder version:
v2.4.5

### Anything else:
➜  ~ subfinder -d google.com -all

        _     __ _         _
____  _| |__ / _(_)_ _  __| |___ _ _
(_-< || | '_ \  _| | ' \/ _  / -_) '_|
/__/\_,_|_.__/_| |_|_||_\__,_\___|_| v2.4.5

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[WRN] By using subfinder, you also agree to the terms of the APIs used.

[INF] Enumerating subdomains for google.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x13d3c52]

goroutine 162 [running]:
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/sitedossier.(*agent).enumerate(0xc000267520, 0x16275e0, 0xc000096060, 0xc000024740, 0x32)
	/Users/harikrish/subfinder/v2/pkg/subscraping/sources/sitedossier/sitedossier.go:40 +0x192
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/sitedossier.(*Source).Run.func1(0xc000267520, 0x16275e0, 0xc000096060, 0x7ff7bfeffab5, 0xa)
	/Users/harikrish/subfinder/v2/pkg/subscraping/sources/sitedossier/sitedossier.go:73 +0xc6
created by github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/sitedossier.(*Source).Run
	/Users/harikrish/subfinder/v2/pkg/subscraping/sources/sitedossier/sitedossier.go:72 +0xc5

**Comment by ehsandeep** [comment]
@harikkrish the issue is you using an outdated version of subfinder.
