### ISSUE TITLE
Error using  ThreatCrowd

### ISSUE THREAD

**Issue by shanfenglan** [projectdiscovery/subfinder#481]
![image](https://user-images.githubusercontent.com/49781523/148708427-0e0e14d8-48dc-453f-88d0-d1d75e3d27bc.png)

But I can access the pages normally

**Comment by LuitelSamikshya** [comment]
Hi @shanfenglan,
Could you specify the subfinder version that you are using?
The issue could not be replicated in the latest version of subfinder v2.4.9.

**Comment by ehsandeep** [comment]
Closing this issue @shanfenglan as this is working fine latest version of the project, another possiblity is that you might be hitting some sort of rate limit by source API.
