### ISSUE TITLE
intelx Data Source Doesn't Work

### ISSUE THREAD

**Issue by DhiyaneshGeek** [projectdiscovery/subfinder#483]
**Describe the bug**
intelix source doesn't work 

**Subfinder version**
 v2.4.9

**Complete command you used to reproduce this**
subfinder -d google.com -sources intelix -v

**Screenshots**
![image](https://user-images.githubusercontent.com/24750220/149775682-f553f277-fdd7-4463-a94c-28dc217cde1b.png)

Valid API Key Present in **.config/subfinder/config.yaml** 

![image](https://user-images.githubusercontent.com/24750220/149775788-e9f69445-e06e-4a05-9bf6-638fbe14562d.png)

**Comment by Mzack9999** [comment]
@DhiyaneshGeek Thanks for opening this issue. It seems like that there is a typo in your command (`intelix` instead of `intelx`). Could you also ensure that your api key is correctly configured as follows (with the hostname as prefix):

```yaml
intelx:
    - host_number.intelx.io:api_key
```

**Comment by DhiyaneshGeek** [comment]
@Mzack9999 Thanks it works fine
