### ISSUE TITLE
Filter invalid input for subdomain discovery

### ISSUE THREAD

**Issue by anio** [projectdiscovery/subfinder#489]
### feature:
It would be great if we had a flag to ignore input (form both `-d` or `-dL`) if it was IP address.

### use case:
Sometimes we pass a list of targets in a bug bounty program scope which is not filtered. subfinder looks for subdomains for IPs and it is a time-waster.

Without this feature we need to filter input for example using `grep`:
```
cat targets.txt | grep -v '^[0-9\.]\+$' | subfinder -all
```

**Comment by ehsandeep** [comment]
It should be supported with the latest release using `exclude-ip` or `ei` flag.
