### ISSUE TITLE
Time limit option

### ISSUE THREAD

**Issue by MirageTurtle** [projectdiscovery/subfinder#491]
### Discussed in https://github.com/projectdiscovery/subfinder/discussions/488

<div type='discussions-op-text'>

<sup>Originally posted by **MirageTurtle** January 21, 2022</sup>
Does subfinder support the feature of time limit? The time limit means the record time. For example, I want to get some subdomains from common crawl in November.

By the way, Which time section does subfinder choose? Or its time rule?

I'll appreciate it if you answer this question.</div>

**Comment by ehsandeep** [comment]
https://github.com/projectdiscovery/subfinder/discussions/488#discussioncomment-2049136
