### ISSUE TITLE
Add source domain to json output

### ISSUE THREAD

**Issue by zerodivisi0n** [projectdiscovery/subfinder#519]
### Please describe your feature request:
Add `input` field with source domain to the json output.
E.g. current output:
```
$ echo hackerone.com | subfinder -silent -json -collect-sources
{"host":"mta-sts.managed.hackerone.com","sources":["crtsh","anubis","alienvault"]}
{"host":"resources.hackerone.com","sources":["alienvault"]}
...
```
Output with feature:
```
echo hackerone.com | subfinder -silent -json -collect-sources
{"host":"mta-sts.managed.hackerone.com","input":"hackerone.com","sources":["crtsh","anubis","alienvault"]}
{"host":"resources.hackerone.com","input":"hackerone.com","sources":["alienvault"]}
...
```
By the way, Amass returns such a field in the output. Why not do the same in Subfinder.

If you don't mind, I'm ready to implement this feature.

### Describe the use case of this feature:
When enumerating multiple domains it is impossible match output domains with the input. This can be useful when enumerating a large number of unrelated domains.

**Comment by ehsandeep** [comment]
@zerodivisi0n thanks for suggesting this useful feature, and please feel free to open a PR for this when possible.

**Comment by zerodivisi0n** [comment]
@ehsandeep Sorry, I missed your reaction. Just opened PR #523 .
