### ISSUE TITLE
API key randomization is not working

### ISSUE THREAD

**Issue by swdbo** [projectdiscovery/subfinder#547]
Hello !

It seems like even if multiple keys are set for a provider in provider-config.yaml, the same unique key will always  be used.

[// We use random selection of api keys from the list of keys supplied.](https://github.com/projectdiscovery/subfinder/blob/8b8f71aea78c82372243d79baafe3dff18627857/v2/pkg/runner/config.go#L84)
I may not fully understand the logic behind the use of `rand.Intn()` in the `GetKeys()` function.
I thought it was a way to randomly distribute calls on each run of subfinder, isn't it ?

If so, I have tested the rand package locally and [on that page](https://pkg.go.dev/math/rand#example-package)
You can see on the link that `answers[rand.Intn(len(answers))]` returns the same value everytime.

It looks like it could be simply resolved by using `rand.Seed(time.Now().UnixNano())` before calling `rand`

**Subfinder version**
v2.5.1

**Comment by ehsandeep** [comment]
@swdbo thanks for reporting this, it is now fixed in the dev version of the project with https://github.com/projectdiscovery/subfinder/pull/550

**Comment by swdbo** [comment]
Well done !
