### ISSUE TITLE
sublist3r source appears to do nothing, api returns null

### ISSUE THREAD

**Issue by b3n-j4m1n** [projectdiscovery/subfinder#584]
### Subfinder version:
Current Version: v2.5.2

### Current Behavior:
The sublist3r api appears to do nothing, no results, only a null response

### Expected Behavior:
sublist3r results

### Steps To Reproduce:
subfinder -d yahoo.com -s sublist3r -proxy http://127.0.0.1:8080

![Untitl111111111ed](https://user-images.githubusercontent.com/19149345/181878909-958126d1-e209-46b9-9de6-4d810da4f3b3.png)

**Comment by ehsandeep** [comment]
@b3n-j4m1n looks like API is not maintained anymore and we can remove it as a source.

**Comment by dogancanbakir** [comment]
@forgedhallpass This issue can be closed, FYI.

**Comment by forgedhallpass** [comment]
> @forgedhallpass This issue can be closed, FYI.

The issue is already marked as completed, and will be closed when it is going to be released.

**Comment by dogancanbakir** [comment]
I see, ty for the info.
