### ISSUE TITLE
Add ResultCallback in runner.Options

### ISSUE THREAD

**Issue by lucy9x** [projectdiscovery/subfinder#593]
### Describe the use case of this feature:
This is very useful when integrating nuclei with other tools to get results

For example:

```go
type Options struct {
    //other options
    .........
    // results are a list subdomain
    ResultCallback func(results []string)
}
```

When a domain is discovered, this option will be called:
```go
if (runner.Options.ResultCallback != nil) {
       runner.Options.ResultCallback(domains)
}
```

**Comment by Mzack9999** [comment]
Notes:
- Large slices of domains might use lots of memory
- Consider also adding `StreamCallback func(chan string)` or invoking the callback on the single domain with additional info like the agent source (ref https://github.com/projectdiscovery/naabu/blob/03034c5928d783a19eb8a55c937e3bbfca4053c9/v2/pkg/runner/options.go#L58)

**Comment by lucy9x** [comment]
> Notes:
> 
> * Large slices of domains might use lots of memory
> * Consider also adding `StreamCallback func(chan string)` or invoking the callback on the single domain with additional info like the agent source (ref https://github.com/projectdiscovery/naabu/blob/03034c5928d783a19eb8a55c937e3bbfca4053c9/v2/pkg/runner/options.go#L58)

Yes. invoking the callback on the single domain is the best choice. This should also be on httpx
