### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by c4ir0** [projectdiscovery/subfinder#640]
when subfinder  requires **go version** `1.17`  to install successfully means when I have go version `1.19 .1 `will not make it install !!! **cause it doesn't** 
![go](https://user-images.githubusercontent.com/108268587/189753657-ec2b4dde-19c4-4660-b697-8a8f125815f0.JPG)

**Comment by ehsandeep** [comment]
@c4ir0 see https://github.com/projectdiscovery/subfinder/discussions/630
