### ISSUE TITLE
Create/aggregate tests for providers that do NOT require an API key

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/subfinder#649]
It seems that we can test all the providers that do not require an API key, with one simple logic that iterates through all and does some assertions like in https://github.com/projectdiscovery/subfinder/pull/648.

**Comment by dogancanbakir** [comment]
I can work on this.

**Comment by forgedhallpass** [comment]
> I can work on this.

Thank you, I've assigned it to you.
