### ISSUE TITLE
Subfinder outputs newlines within crtsh domains

### ISSUE THREAD

**Issue by Cgboal** [projectdiscovery/subfinder#658]
**Describe the bug**
Subfinder seems to parse multi-line domains incorrectly from crt.sh, resulting in newlines being present in the domain names. 

**Subfinder version**
2.5.4 and 2.4.9

**Complete command you used to reproduce this**
```
❯ subfinder -d onsecurity.io -oJ -silent | jq
{
  "host": "r2.onsecurity.io",
  "input": "onsecurity.io",
  "source": "alienvault"
}
{
  "host": "help.onsecurity.io",
  "input": "onsecurity.io",
  "source": "alienvault"
}
{
  "host": "r.onsecurity.io",
  "input": "onsecurity.io",
  "source": "alienvault"
}
{
  "host": "app.onsecurity.io\nonsecurity.io\npartner.app.onsecurity.io",
  "input": "onsecurity.io",
  "source": "crtsh"
}
{
  "host": "partners.uat.dev.onsecurity.io\nuat.dev.onsecurity.io\nuat.dev.onsecurity.io",
  "input": "onsecurity.io",
  "source": "crtsh"
}
```

---

If you want me to fix this i'm happy to do so if it'll lead to faster resolution.

**Comment by forgedhallpass** [comment]
> If you want me to fix this i'm happy to do so if it'll lead to faster resolution.

Feel free to create a PR :)

**Comment by ehsandeep** [comment]
@Cgboal there is fix for it - https://github.com/projectdiscovery/subfinder/pull/662

**Comment by Cgboal** [comment]
Nice one
