### ISSUE TITLE
Subfinder 2.5.4 is intermittently returning email addresses instead of subdomains

### ISSUE THREAD

**Issue by geeknik** [projectdiscovery/subfinder#675]
**Describe the bug**
Subfinder is intermittently returning email addresses instead of subdomains which hinders recon.  There is nothing configured in my provider-config.yaml or my config.yaml.

**Subfinder version**
2.5.4 

**Complete command you used to reproduce this**
echo "af.mil" | subfinder -all -r /opt/dns/resolvers.txt -o /opt/subs/us_air_force/subs.txt

(resolvers.txt is https://public-dns.info/nameserver/us.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/466878/197339235-15dd0297-169d-4954-9b4e-bf0abd645219.png)

**Comment by vzamanillo** [comment]
It is the crtsh source. You can exclude the crtsh source as a temporary workaround.
