### ISSUE TITLE
Failing integration tests for crtsh and waybackarchive

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/subfinder#678]
**Describe the bug**
Integration tests are failing:
- crtsh
- waybackarchive 

ref: https://github.com/projectdiscovery/subfinder/pull/677/checks

- [x] The testing approach output is hardly usable, consider refactoring for better output

**Comment by vzamanillo** [comment]
I think both errors are out of scope because it happens also using a web browser. Maybe implementing a retry policy...
