### ISSUE TITLE
Segfault on ')' and '(' input

### ISSUE THREAD

**Issue by DhiyaneshGeek** [projectdiscovery/subfinder#692]
**Describe the bug**
subfinder crashes when there is a ( , ) in the domain name

**Subfinder version**
subfinder latest version (v2.5.4)

**Complete command you used to reproduce this**
echo '(.example.com' | subfinder

**Screenshots**
![image](https://user-images.githubusercontent.com/24750220/199943105-f8f4341b-d4f6-4c4a-9e74-25712ffe7c4f.png)

**Comment by ehsandeep** [comment]
@DhiyaneshGeek this is fixed in dev version as reported in https://github.com/projectdiscovery/subfinder/issues/671
