### ISSUE TITLE
Error: Ratelimit - Cannot use math.MaxInt64

### ISSUE THREAD

**Issue by zonabansel** [projectdiscovery/subfinder#703]
github.com/projectdiscovery/ratelimit
go/pkg/mod/github.com/projectdiscovery/ratelimit@v0.0.0-20221004232058-7b82379157fa/ratelimit.go:59:13: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in struct literal (overflows)
go/pkg/mod/github.com/projectdiscovery/ratelimit@v0.0.0-20221004232058-7b82379157fa/ratelimit.go:60:13: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in struct literal (overflows)

**Comment by vzamanillo** [comment]
rel [ratelimit#4](https://github.com/projectdiscovery/ratelimit/issues/4)

**Comment by mr-pmillz** [comment]
This is breaking compatibility between the latest Katana and Subfinder go modules. 😩 

```shell
# github.com/projectdiscovery/subfinder/v2/pkg/subscraping
../../go/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.5.4/pkg/subscraping/agent.go:49:61: cannot use rateLimit (variable of type int) as type int64 in argument to ratelimit.New
```

Anybody there 👀 ? @forgedhallpass

**Comment by ehsandeep** [comment]
@mr-pmillz @zonabansel should be fixed with https://github.com/projectdiscovery/subfinder/releases/tag/v2.5.5

**Comment by mr-pmillz** [comment]
Thank you, much appreciated!!! 💯  @ehsandeep
