### ISSUE TITLE
[Issue] Installation Issue

### ISSUE THREAD

**Issue by QueTheWizard** [projectdiscovery/subfinder#711]
**Describe the bug**
Can't install with the command - `go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest`
Getting the following error:
```
go: downloading github.com/projectdiscovery/subfinder v2.5.4+incompatible
go: github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest: module github.com/projectdiscovery/subfinder@latest found (v2.5.4+incompatible), but does not contain package github.com/projectdiscovery/subfinder/v2/cmd/subfinder
```
Go version - go version go1.19.3 darwin/amd64
OS - macOS 12.6.1 (intel chips)

**Subfinder version**
Latest

**Complete command you used to reproduce this**
go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest

**Screenshots**
![2022-11-16_18-06-58](https://user-images.githubusercontent.com/20052885/202232662-a4b433e2-51c2-49ca-b99b-d65b8ff46932.png)

**Comment by QueTheWizard** [comment]
Previous version (v2.5.3) is working with - go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@fa16e09880d437bbccfe624a6b26ae3e593aecda

**Comment by ehsandeep** [comment]
@QueTheWizard should be fixed with https://github.com/projectdiscovery/subfinder/releases/tag/v2.5.5

**Comment by BotAndis** [comment]
I stil have the same error :c
