### ISSUE TITLE
Remove reconcloud and threatminer 

### ISSUE THREAD

**Issue by ShubhamRasal** [projectdiscovery/subfinder#722]
### Subfinder version:
dev 

### Current Behavior:
API's for  reconcloud and threatminer not working. 
reconcloud have cloudflare bot protection to their api and threatminer api is not working anymore. 

### Expected Behavior:
Remove them from subfinder  sources 

https://api.threatminer.org/v2/domain.php?q=hackerone.com&rt=5 
https://recon.cloud/api/search?domain=google.com

**Comment by vzamanillo** [comment]
I think this can be closed by #720

**Comment by tarunKoyalwar** [comment]
already removed in dev
