### ISSUE TITLE
-esd - exclude-subdomain

### ISSUE THREAD

**Issue by PR3R00T** [projectdiscovery/subfinder#739]
Like the -ei flag it would be awesome to have a list on subdomains that are seen as out of scope in a txt file I can pass through with the -esd flag to remove these subdomains out of scope before my automation starts to port scan etc... would stop hunters from scanning by accident on programs.

**Comment by ehsandeep** [comment]
@PR3R00T this feature is already supported with

```
FILTER:
  -m, -match string[]   subdomain or list of subdomain to match (file or comma separated)
  -f, -filter string[]   subdomain or list of subdomain to filter (file or comma separated)
```

```
subfinder -d hackerone.com -filter exclude_subs.txt
```
