### ISSUE TITLE
SecurityTrails Results Enhancement

### ISSUE THREAD

**Issue by DhiyaneshGeek** [projectdiscovery/subfinder#740]
**Describe the bug**

i was manually checking the subdomain count via security-trails source found it misses a lot of results

**Subfinder version**

`Current Version: v2.5.5`

**Complete command you used to reproduce this**

`subfinder -d salesforce.com -sources securitytrails -v`

**Screenshots**

Returns only 2000 subdomains

![image](https://user-images.githubusercontent.com/24750220/209409776-31064e21-0a2b-4039-8c14-67a921c4c1bd.png)

From the Security Trails Surface Browser found it has 500K subdomains

![image](https://user-images.githubusercontent.com/24750220/209410777-cde92b8a-e401-4d22-8688-23ff16365db7.png)

**Comment by vzamanillo** [comment]
It is a Security Trails API limitation

![image](https://user-images.githubusercontent.com/10209695/209432234-68ff09ec-df51-4a34-ae21-9bbd62304914.png)

**Comment by DhiyaneshGeek** [comment]
@vzamanillo Thanks for letting me know !
