### ISSUE TITLE
ratelimit v0.0.1 dependency breaks other tools that use ratelimit v0.0.4 like httpx

### ISSUE THREAD

**Issue by mr-pmillz** [projectdiscovery/subfinder#751]
**Describe the bug**
I'm using the projectdiscovery package httpx natively in go in a project and i cannot upgrade to the latest version of httpx because it depends on ratelimit v0.0.4 and subfinder depends on the outdated ratelimit v0.0.1 package.

Would it be possible to push a new release of subfinder with the latest version of the ratelimit dependency ?
Is it just a matter of time or a particular reason why it hasn't been updated?

```shell
# github.com/projectdiscovery/subfinder/v2/pkg/subscraping                                                         
../../go/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.5.5/pkg/subscraping/agent.go:49:61: cannot use int64(rateLimit) (value of type int64) as type uint in argument to ratelimit.New                                          
```

**Subfinder version**
latest: v2@2.5.5

**Complete command you used to reproduce this**
implement subfinder and httpx natively in golang with the latest versions of each and you're gonna have a bad time. 😉 

**Screenshots**

![image](https://user-images.githubusercontent.com/58376398/216225881-f1bea1ac-21c2-4e8b-8280-731de1abb1c6.png)

**Comment by MarsIsRed** [comment]
I have same issue, any update for this?

**Comment by tarunKoyalwar** [comment]
closing this since it is being tracked at #761
