### ISSUE TITLE
Get error in subscraping\agent.go when compiled subfinder

### ISSUE THREAD

**Issue by nbxiglk0** [projectdiscovery/subfinder#752]
hi,
When I compiled subfinder manually, I found an error with the following error message.  
![image](https://user-images.githubusercontent.com/24366795/216338323-cd7f059f-488c-4275-8077-9e2651eb7f39.png)

![image](https://user-images.githubusercontent.com/24366795/216337842-3c8f1ebe-7aa5-45c4-90f6-130afe53c951.png)

I had to manually modify the library file for type conversion to avoid the error, and I'm not sure if this is a problem with the projectdiscovery/ratelimit library or with the subfinder itself,I compiled the platform is linux amd64, go version is 19.5.

**Comment by nbxiglk0** [comment]
Hi,
Maybe I found the cause of the problem, the problem occurs when I combine multiple projectdiscovery projects, different projects use different versions of the Ratelimit package, for example, subfinder still uses the original 0.0.1 version, while other projects use the latest version (such as kanata), and when compiling, go will The Ratelimit package seems to have some compatibility problems in some places, for example, the type of attributes in Limiter's structure has changed (int64->uint), which is also the location in the error message screenshot, which causes subfinder to not use the latest Ratelimit package, which makes subfinder and other latest projectdiscovery projects can't be combined well.
I would like to ask the developers if they can update the code, otherwise I have to change the source code of subfinder every time I compile the code in a different go environment.

![image](https://user-images.githubusercontent.com/24366795/216743943-7d82a4b4-79d4-42ec-99e4-63da300735c1.png)

**Comment by tarunKoyalwar** [comment]
closing it since it is being tracked in #761
