### ISSUE TITLE
[Issue] Could not get user home directory: user: lookup userid 0: no such file or directory

### ISSUE THREAD

**Issue by thekalinga** [projectdiscovery/subfinder#753]
**Describe the bug**

I ran a container with subfinder to debug my kubernetes environment.

I started a lightweight container containing the following image `nixery.dev/shell/subfinder/dnsx`.

I used this command to start this disposable container in kubernetes

```
kubectl run -it --rm --restart=Never \
        --image=nixery.dev/shell/subfinder/dnsx \
        -- \
        bash
```

When I run `subfinder` within the container, I get the following error

`
[FTL] Could not get user home directory: user: lookup userid 0: no such file or directory
`

I dont get same error when I run `dnsx` in the same environment.

**Subfinder version**

`2.5.5`

**Complete command you used to reproduce this**

`subfinder`

**Screenshots**

![image](https://user-images.githubusercontent.com/452518/216532142-8b73fc15-221c-42f6-a155-45e5e514cb14.png)

**Additional info**

`uname -a` within the container yields  `Linux bash 5.15.0-58-generic #64~20.04.1-Ubuntu SMP Fri Jan 6 16:42:31 UTC 2023 x86_64 GNU/Linux`

I'm using kind (kuberntes in docker) as kubernetes environment. `kind` version (`kind --version`) is `0.17.0`

Kubernetes version (`kubectl version --short`) is

```
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.25.3
```

Docker version (`docker --version`) is `20.10.23, build 7155243`

Docker is running on host Linux with version (`uname -a`)

`Linux hostname 5.15.0-58-generic #64~20.04.1-Ubuntu SMP Fri Jan 6 16:42:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by thekalinga** [comment]
I ran the same container on native docker directly. I am getting the same error here aswell.

```
docker run  -it --rm \                
        nixery.dev/shell/subfinder/dnsx \
        bash
```

Running `subfinder` is yielding the same error.

```
[FTL] Could not get user home directory: user: lookup userid 0: no such file or directory
```

Details of docker & the host its running is listed above.

**Comment by tarunKoyalwar** [comment]
@thekalinga , from your issue description I think the problem is that go is not able to detect user home dir
Can you verify If you are facing issue with latest release https://github.com/projectdiscovery/subfinder/releases/tag/v2.5.6 ?

**Comment by thekalinga** [comment]
The package is not yet updated in the nix repository. So I am still waiting for that to happen.
