### ISSUE TITLE
Code Incompatiblity after installing httpx along with subfinder

### ISSUE THREAD

**Issue by paweloque** [projectdiscovery/subfinder#766]
**Describe the bug**
I'm using subfinder as part of a larger server implemented in go. After installing httpx, there is an incompatibility in subfinder. It manifests after installing https, `go mod tidy` and then `go build`

- `go get -t -u github.com/projectdiscovery/httpx`
- `go mod tidy`
- `go build`

The result of `go build` is: 
```
building...
# github.com/projectdiscovery/subfinder/v2/pkg/subscraping
../../../../go/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.5.5/pkg/subscraping/agent.go:49:61: cannot use int64(rateLimit) (value of type int64) as type uint in argument to ratelimit.New
failed to build, error: exit status 2
```

The problem in the code is in the `package subscraping` in subfinder in the `agent.go` file on line 49: `int64(rateLimit)` and the error is `Cannot use 'int64(rateLimit)' (type int64) as the type uint`
```
// Initiate rate limit instance
if rateLimit > 0 {
	session.RateLimiter = ratelimit.New(context.Background(), --> int64(rateLimit) <--, time.Second)
} else {
	session.RateLimiter = ratelimit.NewUnlimited(context.Background())
}
```

**Subfinder version**
`subfinder/v2 v2.5.5`
`httpx v1.2.7`

**Complete command you used to reproduce this**
- `go get -t -u github.com/projectdiscovery/httpx`
- `go mod tidy`
- `go build`

**Screenshot**
<img width="942" alt="Screenshot 2023-02-21 at 14 55 56" src="https://user-images.githubusercontent.com/1042717/220364804-f6d8ee39-7379-4e59-a674-d513064adab5.png">

**Comment by paweloque** [comment]
Thanks @ehsandeep! I'll point to the dev branch for the moment. What is the timeline for the release?

**Comment by paweloque** [comment]
I've now changed to `subfinder@dev` and `httpx@dev` as an intermediary solution as @ehsandeep proposed:
* go get -t -u github.com/projectdiscovery/httpx@dev
* go get github.com/projectdiscovery/subfinder/v2@dev
Looks fine now.

**Comment by ehsandeep** [comment]
@paweloque - new release is now published - https://github.com/projectdiscovery/subfinder/releases/tag/v2.5.6
