### ISSUE TITLE
Verify that the data source API key is available

### ISSUE THREAD

**Issue by houdinicc** [projectdiscovery/subfinder#792]
### Please describe your feature request:
Use parameters to verify whether the API key in the currently added data source configuration file is available. 

### Describe the use case of this feature:
The API key currently added to the data source configuration file has not been verified, and it is impossible to determine whether the API key can be used normally when running the -all parameter, resulting in incomplete collection of subdomain names..

**Comment by ehsandeep** [comment]
@houdinicc You can use `-v` flag to confirm the same

```console
subfinder -d hackerone.com -v

               __    _____           __         
   _______  __/ /_  / __(_)___  ____/ /__  _____
  / ___/ / / / __ \/ /_/ / __ \/ __  / _ \/ ___/
 (__  ) /_/ / /_/ / __/ / / / / /_/ /  __/ /    
/____/\__,_/_.___/_/ /_/_/ /_/\__,_/\___/_/ v2.5.6

		projectdiscovery.io

[INF] Loading provider config from '/Users/geekboy/.config/subfinder/provider-config.yaml'
[DBG] API key(s) found for bevigil.
[DBG] API key(s) found for c99.
[DBG] API key(s) found for chaos.
[DBG] API key(s) found for dnsrepo.
[DBG] API key(s) found for fullhunt.
[DBG] API key(s) found for github.
[DBG] API key(s) found for quake.
[DBG] API key(s) found for shodan.
[DBG] API key(s) found for zoomeyeapi.
....
```

**Comment by houdinicc** [comment]
nice way
