### ISSUE TITLE
Domains with capitals are not discovered

### ISSUE THREAD

**Issue by ciscomike** [projectdiscovery/subfinder#798]
**Describe the bug**
If a domain is provided by the user that is not capitalized and a source that provides a subdomain contains an FQDN with a domain that is not all lower case (e.g., crt.sh with certs with upper-case SANs, then the Extractor.FindString will not match and return the FQDN since it does a case sensitive match.  I only tested with crtsh but other providers/sources can be affected if they use Extractor.FindString() to match FQDNs.

Apologies for the lack of a PR but it needs more review and there are probably better ways to address the issue that a core dev would know about.

**Subfinder version**
See screenshot.

**Complete command you used to reproduce this**
See screenshot.

**Screenshots**
Patched version on the right.
![image](https://user-images.githubusercontent.com/13560142/227010530-63ce3885-657e-4e0e-8d83-688673ec4ee1.png)

**Patch**
Incomplete and inefficient patch but it's effective for crt.sh.  Makes Extractor.FindString case insensitive and adds a ToLower() to the crtsh scraper to pass additional checks.  Someone ought to ensure other scrapers that can return a domain with one or more capitals have a similar ToLower() added, as needed.

```shell
# report non-lowercase subdomains (at least from crtsh)
sed -i 's/session.Extractor.FindString(subdomain)/strings.ToLower(session.Extractor.FindString(subdomain))/'  v2/pkg/subscraping/sources/crtsh/crtsh.go
sed -i 's/\.Compile(`/\.Compile(`(?i)/' v2/pkg/subscraping/utils.go
cd v2 && make && sudo cp ./subfinder /usr/local/bin/
```

**Comment by ciscomike** [comment]
When I tested this, I recall the ToLower() in my patch was needed for crtsh scraper to get the domain back to the user.  I didn't see this in the commit, so I wanted to double check. Was I mistaken? Reminder, other scrapers may need similar patches.

**Comment by ehsandeep** [comment]
> When I tested this, I recall the ToLower() in my patch was needed for crtsh scraper to get the domain back to the user.  I didn't see this in the commit, so I wanted to double check. Was I mistaken? Reminder, other scrapers may need similar patches.

Thanks for response, Do you have an example that can be used to validate this? Or did you try running from dev branch and still experience the same issue?

**Comment by ciscomike** [comment]
Unfortunately, I can't share the example.  I just tested 2.6.0 against a domain that has capital letters in certs on crt.sh and it fails to report them.

**Comment by ciscomike** [comment]
If you run 

```sh
sed -i 's/session.Extractor.FindString(subdomain)/strings.ToLower(session.Extractor.FindString(subdomain))/' v2/pkg/subscraping/sources/crtsh/crtsh.go
```

This should fix the crtsh.go case as previously mentioned, but the [riddler scraper looks like it still needs a ToLower()](https://github.com/search?q=repo%3Aprojectdiscovery%2Fsubfinder+Extractor.FindString&type=code)

FYI: wayback and commoncrawl scrapers appear to call ToLower() and don't need a fix.

Finally, nvidia.com has multi-case subdomains and can be used for testing the crtsh use case:

```sh
echo nvidia.com |subfinder |grep -iF Ext-LB-Cert1.nvidia.com
```
