### ISSUE TITLE
The session.RateLimiter causes a goroutine leak due to not being closed.

### ISSUE THREAD

**Issue by liapples** [projectdiscovery/subfinder#806]
https://github.com/projectdiscovery/subfinder/blob/bf74523465cd22bbae181145fe0eeb468bee9a18/v2/pkg/passive/passive.go#L24

In this goroutine, a goroutine leak occurs due to the failure to stop session.RateLimiter after it has been created.

**Comment by ehsandeep** [comment]
@liapples thanks for flagging this, should be fixed in dev branch with https://github.com/projectdiscovery/subfinder/pull/846
