### ISSUE TITLE
add source seckrd.com/subdomain-finder

### ISSUE THREAD

**Issue by MetzinAround** [projectdiscovery/subfinder#858]
### Discussed in https://github.com/projectdiscovery/subfinder/discussions/857

<div type='discussions-op-text'>

<sup>Originally posted by **j4vaovo** May 29, 2023</sup>
https://seckrd.com/subdomain-finder</div>

Sorry for the confusion! Making this an issue again.

**Comment by dogancanbakir** [comment]
Hey @j4vaovo,
Thanks for opening the issue. Currently, seckrd.com/subdomain-finder redirects to https://seckrd.com/cgi-sys/suspendedpage.cgi. Therefore, I'm uncertain whether it's a suitable candidate to add as a source. Closing this for now. Let us know if you have any questions.
