### ISSUE TITLE
Issue with digitorus source

### ISSUE THREAD

**Issue by yuanyuu** [projectdiscovery/subfinder#873]
Describe the bug

Using the -dL command, an error message is displayed.

```console
panic: runtime error: invalid memory address or nil pointer dereference 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc3c7b4] 
goroutine 234 [running]: github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus.(*Source).Run.func1() /subfinder-main/v2/pkg/subscraping/sources/digitorus/digitorus.go:36 +0x255 created by github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus.(*Source).Run /subfinder-main/v2/pkg/subscraping/sources/digitorus/digitorus.go:28 +0x125”
```
I want to know what caused this mistake and whether it can be avoided. What should I do if I can avoid errors? I would appreciate it if you could tell me the solution

Subfinder version

2.6.0

Complete command you used to reproduce this

subfinder -all -silent -dL test.txt -o results.txt

All the best

**Comment by ehsandeep** [comment]
@yuanyuu can you share the complete error log? or cmd/input that can be used to reproduce?

**Comment by yuanyuu** [comment]
@ehsandeep
Thank you very much for replying to me, I spent some time looking for the error message, the following is the complete error message:

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc3c7b4]
goroutine 234 [running]:
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus.(*Source).Run.func1()
/subfinder-main/v2/pkg/subscraping/sources/digitorus/digitorus.go:36 +0x255
created by github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus.(*Source).Run
/subfinder-main/v2/pkg/subscraping/sources/digitorus/digitorus.go:28 +0x125”`

Since this is my first time using github's reply function, I thought carefully and then typeset, wondering if "@" was successful? In addition, my English is not very good, I do not know whether I can express my meaning correctly, and there may be some incorrect operations, I hope you can bear with me.
Look forward to your favourable reply

**Comment by ehsandeep** [comment]
@yuanyuu thank you for sharing more information and don't worry about language, is it possible for you to share what's inside in the `test.txt`?

**Comment by yuanyuu** [comment]
@ehsandeep
I tried the command again and the error message was the same. The contents of the test.txt file are as follows:
```
juzimi.com
kankanwu.com
qlchat.com
futunn.com
pingan.com.cn
genban.org
iczsq.com
nsw88.com
imeiju.cc
glofang.com
kuaiji.com
kocla.com
winit.com.cn
china-10.com
25pp.com
xxbiquge.com
ky188.cn
cgbchina.com.cn
ecar168.cn
eascs.com
chenguang.com.cn
cedo.cn
52swine.com
iyjnews.com
xinm123.com
mzdsxyfgmjnh.com
51g3.net
xinrongkang.com
jinfuren.tv
cscec4b.com.cn
```
I wonder if the reason for the error might be that the number of variable "Errors" in "digitorus.go" exceeded the limit, so an error was reported?

**Comment by sqhjcaasyndui** [comment]
version：v2.5.9
errer：
```java
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x165b9d5]

goroutine 759 [running]:
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus.(*Source).Run.func1()
        /home/runner/work/subfinder/subfinder/v2/pkg/subscraping/sources/digitorus/digitorus.go:36 +0x255
created by github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus.(*Source).Run
        /home/runner/work/subfinder/subfinder/v2/pkg/subscraping/sources/digitorus/digitorus.go:28 +0x125
```
cmd：subfinder.exe -dl url.txt -o icpurls.txt
I also encountered this error, but I ran the domain that reported the error separately_ URL, the problem does not occur.


@ehsandeep

**Comment by ProViDoR** [comment]
i have the same problem  with basic cmd subfinder -d anydomain

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc6e595]

goroutine 113 [running]:
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus.(*Source).Run.func1()
        /home/runner/work/subfinder/subfinder/v2/pkg/subscraping/sources/digitorus/digitorus.go:36 +0x255
created by github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus.(*Source).Run
        /home/runner/work/subfinder/subfinder/v2/pkg/subscraping/sources/digitorus/digitorus.go:28 +0x125

**Comment by loveshell** [comment]
me,too.
```
 subfinder -d baidu.com -all -t 100

               __    _____           __         
   _______  __/ /_  / __(_)___  ____/ /__  _____
  / ___/ / / / __ \/ /_/ / __ \/ __  / _ \/ ___/
 (__  ) /_/ / /_/ / __/ / / / / /_/ /  __/ /    
/____/\__,_/_.___/_/ /_/_/ /_/\__,_/\___/_/

                projectdiscovery.io

[INF] Loading provider config from /root/.config/subfinder/provider-config.yaml
[INF] Enumerating subdomains for baidu.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc6e595]

goroutine 32 [running]:
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus.(*Source).Run.func1()
        /home/runner/work/subfinder/subfinder/v2/pkg/subscraping/sources/digitorus/digitorus.go:36 +0x255
created by github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus.(*Source).Run
        /home/runner/work/subfinder/subfinder/v2/pkg/subscraping/sources/digitorus/digitorus.go:28 +0x125
```

**Comment by ehsandeep** [comment]
@yuanyuu @loveshell @ProViDoR @sqhjcaasyndui till the time this bug is fixed, feel free to use`-es digitorus` option to exclude this source.

**Comment by ehsandeep** [comment]
@yuanyuu fixed in the latest release.
