### ISSUE TITLE
[signal 0xc0000005 code=0x0 addr=0x10 pc=0xfdb9f5]

### ISSUE THREAD

**Issue by qiuluo-oss** [projectdiscovery/subfinder#893]
[signal 0xc0000005 code=0x0 addr=0x10 pc=0xfdb9f5]

goroutine 3143 [running]:
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus.(*Source).Run.func1()
        /home/runner/work/subfinder/subfinder/v2/pkg/subscraping/sources/digitorus/digitorus.go:36 +0x255
created by github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus.(*Source).Run
        /home/runner/work/subfinder/subfinder/v2/pkg/subscraping/sources/digitorus/digitorus.go:28 +0x125
![image](https://github.com/projectdiscovery/subfinder/assets/72497146/a2354946-4045-4f62-ae88-63ca11b83afc)

**Comment by MetzinAround** [comment]
Hi. @qiuluo-oss , do you have a question?

**Comment by ehsandeep** [comment]
@qiuluo-oss duplicate of https://github.com/projectdiscovery/subfinder/issues/873, already fixed in the dev branch.

cc @MetzinAround
