### ISSUE TITLE
[panic] in /pkg/subscraping/sources/digitorus/digitorus.go:36

### ISSUE THREAD

**Issue by liapples** [projectdiscovery/subfinder#894]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd4e375]

goroutine 125597 [running]:
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus.(*Source).Run.func1()
        D:/GOPATH/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.5.9/pkg/subscraping/sources/digitorus/digitorus.go:36 +0x255
created by github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus.(*Source).Run
        D:/GOPATH/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.5.9/pkg/subscraping/sources/digitorus/digitorus.go:28 +0x125

**Comment by ehsandeep** [comment]
@liapples fixed in the latest release.
