### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by EXTENSION456** [projectdiscovery/subfinder#895]
So whenever i run subfinder to enumerate subdomains , i get an error after it finds some of the subdomains.
The error:-
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7aa684]
goroutine 61 [running]:
github.com/projectdiscovery/subfinder/pkg/subscraping/sources/github.(*Source).enumerate(0xdca6b0, 0xa39820, 0xc000034960, 0xc000156000, 0x3f, 0xc00015a0a0, 0xc000122140, 0xc0000c4dc0, 0xc00010e720)
github.com/projectdiscovery/subfinder/pkg/subscraping/sources/github/github.go:126 +0x9a4
github.com/projectdiscovery/subfinder/pkg/subscraping/sources/github.(*Source).Run.func1(0xc0000c4dc0, 0xc00010e720, 0x7ffc7e39e2a6, 0xb, 0xdca6b0, 0xa39820, 0xc000034960)
 github.com/projectdiscovery/subfinder/pkg/subscraping/sources/github/github.go:53 +0x18f
created by github.com/projectdiscovery/subfinder/pkg/subscraping/sources/github.(*Source).Run
github.com/projectdiscovery/subfinder/pkg/subscraping/sources/github/github.go:43 +0xa3
                                                                             
The version of my subfinder is:-              2.3.8
Command to reproduce:-
                          subfinder -d www.xyz.com ( let xyz can be any domain )

**Screenshots**
![Screenshot_2023-07-09_08_51_55](https://github.com/projectdiscovery/subfinder/assets/48002840/9b01df9e-3a2e-4a7f-b083-ca24e0ee53d8)

![Screenshot_2023-07-09_08_52_03](https://github.com/projectdiscovery/subfinder/assets/48002840/e4df2ee9-a6e9-48d9-b8d1-3b00923dfa4d)

Please look into this

**Comment by j4vaovo** [comment]
````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc92595]

goroutine 71 [running]:
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus.(*Source).Run.func1()
        /root/go/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.6.0/pkg/subscraping/sources/digitorus/digitorus.go:36 +0x255
created by github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus.(*Source).Run
        /root/go/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.6.0/pkg/subscraping/sources/digitorus/digitorus.go:28 +0x125
````

**Comment by seeCURE** [comment]
Having the same issue while using this command `subfinder -dL roots.txt -o output.txt` "roots.txt" contained +1k domains. When the subfinder reached near ~150th domain it stopped and threw following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x102a6e750]

goroutine 168636 [running]:
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus.(*Source).Run.func1()
	/home/runner/work/subfinder/subfinder/v2/pkg/subscraping/sources/digitorus/digitorus.go:36 +0x180
created by github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus.(*Source).Run
	/home/runner/work/subfinder/subfinder/v2/pkg/subscraping/sources/digitorus/digitorus.go:28 +0x128
```
Thanks!

**Comment by MetzinAround** [comment]
@ehsandeep this seems similar to the issue https://github.com/projectdiscovery/subfinder/issues/873 but it isn't about digitorous this time. 

@seeCURE and @j4vaovo, the above link does have info about your issue since it's from the digitorous pkg. But the OP isn't experiencing it in the same pkg.

**Comment by seeCURE** [comment]
Thanks @MetzinAround for pointing me to #873. The temporary [solution](https://github.com/projectdiscovery/subfinder/issues/873#issuecomment-1602203443) provided by @ehsandeep which is to exclude `digitorous` source seems to work.

I appreciate all the work PD team is doing for the community!

Thanks!

**Comment by ehsandeep** [comment]
@EXTENSION456 that's because you are using way older version of subfinder, use latest version to avoid crashes.
