### ISSUE TITLE
[Issue] SecurityTrails API doesn't work

### ISSUE THREAD

**Issue by Vulpurpureus** [projectdiscovery/subfinder#900]
**Bug Description**
When trying to enumerate subdomains using the SecurityTrails source for multiple different domains with many subdomains, I get the message "Found 0 subdomains". The issue is only with SecurityTrails because the other sources work(the API key was configured in the config file, and of course, on the SecurityTrails website you can find the subdomains).
In addition, I tried using the Curl method from the API documentation and it worked(I have enough API quotas).

**Subfinder version**
Version v2.6.0 (latest)

**The command I used to reproduce this**
subfinder -d tesla.com -s securitytrails

**Screenshots**
https://i.imgur.com/xrEjSCn.png

**Comment by MetzinAround** [comment]
hi @Vulpurpureus , I got a SecurityTrails key and tried this as well and got the same error of no subdomains. 

Is it happening with any other domains other than tesla for you?

**Comment by MetzinAround** [comment]
Ok, I was able to verify that subfinder found nothing with SecurityTrails but another tool using SecurityTrails was able to find subdomains. 

@ehsandeep Is this something you've seen before?

**Comment by MetzinAround** [comment]
POSSIBLY related to a previous error involving SecurityTrails

https://github.com/projectdiscovery/subfinder/issues/860

**Comment by ehsandeep** [comment]
@Vulpurpureus fixed in the latest release.
