### ISSUE TITLE
bufferover no longer works

### ISSUE THREAD

**Issue by motoko-ayanami** [projectdiscovery/subfinder#915]
### 
Subfinder version: v2.6.1

### Current Behavior:
`subfinder -d example.com -s bufferover`
This command returns 0 results when using the api key.

**Comment by MetzinAround** [comment]
Hi! Thanks for the issue. 
Could you show us the complete output? Is it throwing any errors or just returning zero results?

**Comment by motoko-ayanami** [comment]
It looks like it took some time for the API key to activate. I ran the exact command as last night and now it's working.
