### ISSUE TITLE
PassiveTotal api no longer works

### ISSUE THREAD

**Issue by motoko-ayanami** [projectdiscovery/subfinder#920]
Version v2.6.1

PassiveTotal was bought out by Microsoft and doesn't seem to be the same credentials anymore.

![passivetotal](https://github.com/projectdiscovery/subfinder/assets/122310140/ba79f207-2a0f-49cb-9158-278c9e7669ca)

**Comment by DhiyaneshGeek** [comment]
Hi @dogancanbakir @motoko-ayanami 

passive total works for me , users need to sign up at https://community.riskiq.com and visit setting page , hope this helps 

![image](https://github.com/projectdiscovery/subfinder/assets/24750220/1fc6fc2b-4d75-4736-9955-1f21ef9d41c4)


Reference: https://dhiyaneshgeek.github.io/bug/bounty/2020/02/06/recon-with-me/

**Comment by dogancanbakir** [comment]
After reviewing again, we found that the old users can still generate API credentials which they can use for PassiveTotal source, but the same wasn't possible with the new users. I updated the PR by adding a warning to inform users of this.
