### ISSUE TITLE
New Output Type for OSINT Engagement Reporting (-oI)

### ISSUE THREAD

**Issue by codingo** [projectdiscovery/subfinder#97]
When working on an OSINT engagement I want to include subdomain information in supplemental data of my reporting. I believe subfinder could provide an output type to supplement this. I would see this as working similar to the following:
```
<source> <subdomain> <currently active>
```

For example:

```
[BAIDU] testdomain.yahoo.com (Currently active)
[ASK] testdomain2.yahoo.com (No longer active)
```

**Comment by codingo** [comment]
Consideration would need to be made when implementing this t hat if it is run with the -nW flag a warning should be raised that subdomains that no longer resolve will be excluded from results.

**Comment by ProDigySML** [comment]
Hey @codingo! I think that is a really good idea! That would really add value and to the tool and make life a fair bit easier! Stating the source helps a tester inform where it was found and can allow further manual enumeration too.

**Comment by codingo** [comment]
Further to this, I think if something is found over multiple sources it should present as:

```
[BAIDU] [ASK] testdomain2.yahoo.com (No longer active)
```

**Comment by Ice3man543** [comment]
Hey, i don't believe this would be useful for general people. Also, it would require too much work to be implemented. Hence closing this issue now. Feel free to reopen it!
