### ISSUE TITLE
Subfinder outputs are appending domain name in output because of chaos

### ISSUE THREAD

**Issue by sanjai-AK47** [projectdiscovery/subfinder#999]
### Reason
I have analysed and found that chaos output changed, instead of appending domain name with subdomain you can simply
avoiding adding the domain name

### Chaos changes:

Previous ouput of chaos :   *.cloud or cloud

Latest output of chaos : *.cloud.goog.com or cloud.google.com

### Steps To Reproduce:
```bash
subfinder -d google.com
```

### Anything else:
Yeah I have found this when I was testing in my tool [Subdominator](https://github.com/sanjai-AK47/Subdominator) I got the results like subfinder ok then I clearly checked and found the changes happened in chaos-client output

**Comment by ravlio** [comment]
@sanjai-AK47 thanks for report! Fixed.

**Comment by sanjai-AK47** [comment]
@ravlio Your Welcome

**Comment by m3hrajbhat** [comment]
Subfinder version : 2.13.0 (latest)
Bug: subfinder gives output like for example: subdomain.google.com.google.com
Reason: Chaos api

I have removed chaos api in provider-config.yaml and got the clean results.
